#pragma once
#include "pch.h"

namespace database
{
    static std::vector<std::string> db_items =
    {
     "Accessory_NormalResist_1",
     "Accessory_NormalResist_2",
     "Accessory_NormalResist_3",
     "Accessory_AquaResist_1",
     "Accessory_AquaResist_2",
     "Accessory_AquaResist_3",
     "Accessory_AT_1",
     "Accessory_AT_2",
     "Accessory_AT_3",
     "Accessory_CoolResist_1",
     "Accessory_CoolResist_2",
     "Accessory_CoolResist_3",
     "Accessory_DarkResist_1",
     "Accessory_DarkResist_2",
     "Accessory_DarkResist_3",
     "Accessory_defense_1",
     "Accessory_defense_2",
     "Accessory_defense_3",
     "Accessory_DragonResist_1",
     "Accessory_DragonResist_2",
     "Accessory_DragonResist_3",
     "Accessory_EarthResist_1",
     "Accessory_EarthResist_2",
     "Accessory_EarthResist_3",
     "Accessory_FireResist_1",
     "Accessory_FireResist_2",
     "Accessory_FireResist_3",
     "Accessory_HeatResist_1",
     "Accessory_HeatResist_2",
     "Accessory_HeatResist_3",
     "Accessory_HP_1",
     "Accessory_HP_2",
     "Accessory_HP_3",
     "Accessory_IceResist_1",
     "Accessory_IceResist_2",
     "Accessory_IceResist_3",
     "Accessory_LeafResist_1",
     "Accessory_LeafResist_2",
     "Accessory_LeafResist_3",
     "Accessory_ThunderResist_1",
     "Accessory_ThunderResist_2",
     "Accessory_ThunderResist_3",
     "Accessory_WorkSpeed_1",
     "Accessory_WorkSpeed_2",
     "Accessory_WorkSpeed_3",
     "AirGrapplingGun",
     "AnimalSkin",
     "AnimalSkin2",
     "Antibiotic_Good",
     "Antibiotic_Normal",
     "Antibiotic_Super",
     "Arrow",
     "Arrow_Poison",
     "Arrow_Fire",
     "AssaultRifle_Default1",
     "Axe_Tier_00",
     "Axe_Tier_01",
     "Axe_Tier_02",
     "Axe_Tier_03",
     "Baked_Berries",
     "Baked_Potato",
     "Baked_Unko",
     "BakedMushroom",
     "Bandage_Good",
     "Bandage_Normal",
     "Bandage_Super",
     "Bat",
     "Bat2",
     "MeatCutterKnife",
     "BAT_NPC",
     "Beer",
     "Berries",
     "Berries2",
     "BerrySeeds",
     "BLT",
     "BOSS_1",
     "Bow",
     "Bow_Fifth",
     "Bow_Triple",
     "BowGun",
     "BowGun_Fire",
     "BowGun_Poison",
     "CaptureRope",
     "Carbonara",
     "CashFang",
     "CashScales",
     "Charcoal",
     "CheeseBurger",
     "Claws",
     "Claws2",
     "ClawsPendant",
     "Cloth",
     "Cloth2",
     "ClothArmor",
     "ClothHat",
     "Coal",
     "Computer",
     "CopperArmor",
     "CopperHelmet",
     "CopperIngot",
     "CopperOre",
     "Corn",
     "CornSoup",
     "CrudeOil",
     "Curry",
     "DebugHandgun",
     "Diamond",
     "DoubleBarrelShotgun",
     "Eemerald",
     "Egg",
     "ElecBaton",
     "ElectronicCircuit",
     "EnergyDrink",
     "ExplosiveBullet",
     "Fang",
     "Fang2",
     "FangNecklace",
     "FarmCrop_Tmp",
     "Fiber",
     "FishingRod_Good",
     "FishingRod_Legendary",
     "FishingRod_Old",
     "FishingRod_Super",
     "FishMeat",
     "FishMeat2",
     "Flint",
     "FriedEggs",
     "FurArmor",
     "FurHelmet",
     "GasMask",
     "Glider_Good",
     "Glider_Legendary",
     "Glider_Old",
     "Glider_Super",
     "Grape",
     "GrilledFish",
     "GrilledMeat",
     "Gunpowder",
     "Gunpowder2",
     "Hamburger",
     "HandGun_Default",
     "HandgunBullet",
     "Herbs",
     "HomingSphereLauncher",
     "Honey",
     "Sweet",
     "Hop",
     "HotMilk",
     "IronArmor",
     "IronHelmet",
     "IronIngot",
     "IronOre",
     "JamBun",
     "Kitsunebi_Fire",
     "LargeBullet",
     "LaserBullet",
     "LaserRifle",
     "Launcher_Default",
     "Launcher_Meat",
     "Leather",
     "Leather2",
     "Lettuce",
     "LettuceSeeds",
     "LightzHelmet",
     "LuxuryMedicines",
     "LuxuryOmelette",
     "MachineParts",
     "MachineParts2",
     "MakeshiftHandgun",
     "meat",
     "Meat2",
     "Medicines",
     "Milk",
     "MindControlDrug",
     "Money",
     "Mushroom",
     "NightVisionGoggles",
     "NPC_WEAPON",
     "Omelet",
     "Pal_crystal_L",
     "Pal_crystal_S",
     "PAL_Growth_Stone_L",
     "PAL_Growth_Stone_M",
     "PAL_Growth_Stone_S",
     "PAL_Growth_Stone_XL",
     "PalBox_ticket",
     "PalCrystal_Ex",
     "PalEgg",
     "PalEgg_Dark_01",
     "PalEgg_Dark_02",
     "PalEgg_Dark_03",
     "PalEgg_Dark_04",
     "PalEgg_Dark_05",
     "PalEgg_Dragon_01",
     "PalEgg_Dragon_02",
     "PalEgg_Dragon_03",
     "PalEgg_Dragon_04",
     "PalEgg_Dragon_05",
     "PalEgg_Earth_01",
     "PalEgg_Earth_02",
     "PalEgg_Earth_03",
     "PalEgg_Earth_04",
     "PalEgg_Earth_05",
     "PalEgg_Electricity_01",
     "PalEgg_Electricity_02",
     "PalEgg_Electricity_03",
     "PalEgg_Electricity_04",
     "PalEgg_Electricity_05",
     "PalEgg_Fire_01",
     "PalEgg_Fire_02",
     "PalEgg_Fire_03",
     "PalEgg_Fire_04",
     "PalEgg_Fire_05",
     "PalEgg_Ice_01",
     "PalEgg_Ice_02",
     "PalEgg_Ice_03",
     "PalEgg_Ice_04",
     "PalEgg_Ice_05",
     "PalEgg_Leaf_01",
     "PalEgg_Leaf_02",
     "PalEgg_Leaf_03",
     "PalEgg_Leaf_04",
     "PalEgg_Leaf_05",
     "PalEgg_Normal_01",
     "PalEgg_Normal_02",
     "PalEgg_Normal_03",
     "PalEgg_Normal_04",
     "PalEgg_Normal_05",
     "PalEgg_Water_01",
     "PalEgg_Water_02",
     "PalEgg_Water_03",
     "PalEgg_Water_04",
     "PalEgg_Water_05",
     "PalItem_ToSell_01",
     "PalItem_ToSell_02",
     "PalItem_ToSell_03",
     "PalItem_ToSell_04",
     "PalItem_ToSell_05",
     "PalOil",
     "PalItem_ColorfulBird",
     "PalItem_PlantSlime",
     "PalItem_CaptainPenguin",
     "PalItem_CatMage",
     "PalSphere",
     "PalSphere_Giga",
     "PalSphere_Legend",
     "PalSphere_Master",
     "PalSphere_Mega",
     "PalSphere_Tera",
     "PalSphere_Robbery",
     "PalSphere_Debug",
     "PalUpgradeStone",
     "PalUpgradeStone2",
     "PalUpgradeStone3",
     "Pan",
     "PenguinLauncher",
     "Pickaxe_Tier_00",
     "Pickaxe_Tier_01",
     "Pickaxe_Tier_02",
     "Pickaxe_Tier_03",
     "Pizza",
     "Plastic",
     "Polymer",
     "Potage",
     "Potato",
     "PotatoSeedPotatoes",
     "PumpActionShotgun",
     "Pumpkin",
     "PV_ITEMS",
     "Quartz",
     "RecurveBow",
     "Relic",
     "RepairKit",
     "RifleBullet",
     "Ruby",
     "Salad",
     "Sandwich",
     "Sapphire",
     "Scales",
     "Scales2",
     "SeafoodSoup",
     "Seed_Tmp",
     "Sharkkid_Scale",
     "Shield_01",
     "Shield_02",
     "Shield_03",
     "Shield_04",
     "Shield_05",
     "Shield_06",
     "ShotgunBullet",
     "RoughBullet",
     "MachingunBullet",
     "AssaultRifleBullet",
     "MagnumBullet",
     "SingleShotRifle",
     "SkillCard_PowerShot",
     "SkillCard_PowerBall",
     "SkillCard_HyperBeam",
     "SkillCard_AirCanon",
     "SkillCard_SelfDestruct",
     "SkillCard_WindCutter",
     "SkillCard_GrassTornado",
     "SkillCard_SolarBeam",
     "SkillCard_SeedMachinegun",
     "SkillCard_RootAttack",
     "SkillCard_SeedMine",
     "SkillCard_WaterGun",
     "SkillCard_WaterBall",
     "SkillCard_HydroPump",
     "SkillCard_AquaJet",
     "SkillCard_BubbleShot",
     "SkillCard_AcidRain",
     "SkillCard_FireBlast",
     "SkillCard_Flamethrower",
     "SkillCard_FireBall",
     "SkillCard_FlareArrow",
     "SkillCard_FireSeed",
     "SkillCard_Inferno",
     "SkillCard_FlareTornado",
     "SkillCard_ElecWave",
     "SkillCard_Thunderbolt",
     "SkillCard_LineThunder",
     "SkillCard_ThunderFunnel",
     "SkillCard_SpreadPulse",
     "SkillCard_LockonLaser",
     "SkillCard_ThunderBall",
     "SkillCard_ThreeThunder",
     "SkillCard_ThrowRock",
     "SkillCard_SandTornado",
     "SkillCard_RockLance",
     "SkillCard_MudShot",
     "SkillCard_StoneShotgun",
     "SkillCard_IceMissile",
     "SkillCard_BlizzardLance",
     "SkillCard_IcicleThrow",
     "SkillCard_DarkWave",
     "SkillCard_ShadowBall",
     "SkillCard_Psychokinesis",
     "SkillCard_PoisonShot",
     "SkillCard_GhostFlame",
     "SkillCard_DarkLaser",
     "SkillCard_DragonBreath",
     "SkillCard_DragonCanon",
     "SkillCard_DragonWave",
     "SkillCard_DragonMeteor",
     "SkillCard_LightningStrike",
     "SkillCard_IceBlade",
     "SkillCard_FrostBreath",
     "SkillUnlock_Alpaca",
     "SkillUnlock_AmaterasuWolf",
     "SkillUnlock_Anubis",
     "SkillUnlock_BadCatgirl",
     "SkillUnlock_BirdDragon",
     "SkillUnlock_BlackCentaur",
     "SkillUnlock_BlackFurDragon",
     "SkillUnlock_BlackGriffon",
     "SkillUnlock_BlackMetalDragon",
     "SkillUnlock_BlueDragon",
     "SkillUnlock_Boar",
     "SkillUnlock_CaptainPenguin",
     "SkillUnlock_Carbunclo",
     "SkillUnlock_ColorfulBird",
     "SkillUnlock_DarkMutant",
     "SkillUnlock_Deer",
     "SkillUnlock_DreamDemon",
     "SkillUnlock_DrillGame",
     "SkillUnlock_Eagle",
     "SkillUnlock_ElecLion",
     "SkillUnlock_ElecPanda",
     "SkillUnlock_FairyDragon",
     "SkillUnlock_FeatherOstrich",
     "SkillUnlock_FengyunDeeper",
     "SkillUnlock_FireKirin",
     "SkillUnlock_FlameBuffalo",
     "SkillUnlock_FlowerDinosaur",
     "SkillUnlock_FlowerRabbit",
     "SkillUnlock_FlyingManta",
     "SkillUnlock_Garm",
     "SkillUnlock_GhostBeast",
     "SkillUnlock_GoldenHorse",
     "SkillUnlock_GrassMammoth",
     "SkillUnlock_GrassPanda",
     "SkillUnlock_GuardianDog",
     "SkillUnlock_HadesBird",
     "SkillUnlock_HawkBird",
     "SkillUnlock_Hedgehog",
     "SkillUnlock_HerculesBeetle",
     "SkillUnlock_Horus",
     "SkillUnlock_IceDeer",
     "SkillUnlock_IceFox",
     "SkillUnlock_IceHorse",
     "SkillUnlock_JetDragon",
     "SkillUnlock_KingAlpaca",
     "SkillUnlock_KingBahamut",
     "SkillUnlock_Kirin",
     "SkillUnlock_Kitsunebi",
     "SkillUnlock_LazyDragon",
     "SkillUnlock_LilyQueen",
     "SkillUnlock_Manticore",
     "SkillUnlock_Monkey",
     "SkillUnlock_MopKing",
     "SkillUnlock_NaughtyCat",
     "SkillUnlock_NegativeOctopus",
     "SkillUnlock_Penguin",
     "SkillUnlock_RaijinDaughter",
     "SkillUnlock_RedArmorBird",
     "SkillUnlock_SaintCentaur",
     "SkillUnlock_SakuraSaurus",
     "SkillUnlock_Serpent",
     "SkillUnlock_SkyDragon",
     "SkillUnlock_Suzaku",
     "SkillUnlock_ThunderBird",
     "SkillUnlock_ThunderDog",
     "SkillUnlock_Umihebi",
     "SkillUnlock_VolcanicMonster",
     "SkillUnlock_WeaselDragon",
     "SkillUnlock_WingGolem",
     "SkillUnlock_WindChimes",
     "SkillUnlock_Yeti",
     "SkillUnlock_Umihebi_Fire",
     "SkillUnlock_Deer_Ground",
     "SkillUnlock_Hedgehog_Ice",
     "SkillUnlock_FlowerDinosaur_Electric",
     "SkillUnlock_GrassMammoth_Ice",
     "SkillUnlock_LazyDragon_Electric",
     "SkillUnlock_FireKirin_Dark",
     "SkillUnlock_SakuraSaurus_Water",
     "SkillUnlock_FairyDragon_Water",
     "SkillUnlock_Manticore_Dark",
     "SkillUnlock_Suzaku_Water",
     "SkillUnlock_Serpent_Ground",
     "SkillUnlock_VolcanicMonster_Ice",
     "SkillUnlock_IceHorse_Dark",
     "SkillUnlock_GrassPanda_Electric",
     "SkillUnlock_Yeti_Grass",
     "SkillUnlock_KingAlpaca_Ice",
     "SkillUnlock_BirdDragon_Ice",
     "SkillUnlock_WindChimes_Ice",
     "SmallBullet",
     "SniperRifle_Default",
     "SphereLauncher",
     "SphereLauncher_Once",
     "StealArmor",
     "StealHelmet",
     "StealIngot",
     "Stew",
     "Stone",
     "Sulfur",
     "Sword",
     "TechnologyBook_G1",
     "TechnologyBook_G2",
     "TechnologyBook_G3",
     "ThrowStone",
     "FragGrenade",
     "FragGrenade_Fire",
     "FragGrenade_Ice",
     "FragGrenade_Elec",
     "Tomato",
     "TomatoSeeds",
     "Torch",
     "Unko_L",
     "Unko_S",
     "VenisonBoiledInTomato",
     "WaterBucket",
     "WazaTest",
     "WeakerBow",
     "Bow_Fire",
     "Bow_Poison",
     "Wheat",
     "WheatSeeds",
     "Flour",
     "Wine",
     "Wood",
     "Wool",
     "ElectricOrgan",
     "Venom",
     "FireOrgan",
     "IceOrgan",
     "Bone",
     "Sand",
     "Silicon",
     "Cement",
     "CarbonFiber",
     "Horn",
     "Spear",
     "Spear_2",
     "Spear_3",
     "Lantern",
     "AutoMealPouch_Tier1",
     "AutoMealPouch_Tier2",
     "AutoMealPouch_Tier3",
     "AutoMealPouch_Tier4",
     "AutoMealPouch_Tier5",
     "GrapplingGun_1",
     "GrapplingGun_2",
     "GrapplingGun_3",
     "GrapplingGun_4",
     "Head001",
     "Head002",
     "Head003",
     "Head004",
     "Head005",
     "Head006",
     "Head007",
     "Head008",
     "Head009",
     "Head010",
     "Head011",
     "Head012",
     "Head013",
     "Head014",
     "Head015",
     "Head016",
     "Head017",
     "MateItem01",
     "TreasureBoxKey01",
     "TreasureBoxKey02",
     "TreasureBoxKey03",
     "Musket",
     "FriedVegetables",
     "HotDog",
     "Pancake",
     "MarinatedMushrooms",
     "MushroomSoup",
     "MushroomStew",
     "MeatSauce",
     "Cake",
     "WeakerBow_2",
     "WeakerBow_3",
     "WeakerBow_4",
     "WeakerBow_5",
     "BowGun_2",
     "BowGun_3",
     "BowGun_4",
     "BowGun_5",
     "HandGun_Default_2",
     "HandGun_Default_3",
     "HandGun_Default_4",
     "HandGun_Default_5",
     "AssaultRifle_Default2",
     "AssaultRifle_Default3",
     "AssaultRifle_Default4",
     "AssaultRifle_Default5",
     "PumpActionShotgun_2",
     "PumpActionShotgun_3",
     "PumpActionShotgun_4",
     "PumpActionShotgun_5",
     "Launcher_Default_2",
     "Launcher_Default_3",
     "Launcher_Default_4",
     "Launcher_Default_5",
     "Blueprint_ClothArmorHeat_2",
     "Blueprint_ClothArmorHeat_3",
     "Blueprint_ClothArmorHeat_4",
     "Blueprint_ClothArmorHeat_5",
     "Blueprint_ClothArmorCold_2",
     "Blueprint_ClothArmorCold_3",
     "Blueprint_ClothArmorCold_4",
     "Blueprint_ClothArmorCold_5",
     "Blueprint_FurArmorHeat_2",
     "Blueprint_FurArmorHeat_3",
     "Blueprint_FurArmorHeat_4",
     "Blueprint_FurArmorHeat_5",
     "Blueprint_FurArmorCold_2",
     "Blueprint_FurArmorCold_3",
     "Blueprint_FurArmorCold_4",
     "Blueprint_FurArmorCold_5",
     "Blueprint_CopperArmorHeat_2",
     "Blueprint_CopperArmorHeat_3",
     "Blueprint_CopperArmorHeat_4",
     "Blueprint_CopperArmorHeat_5",
     "Blueprint_CopperArmorCold_2",
     "Blueprint_CopperArmorCold_3",
     "Blueprint_CopperArmorCold_4",
     "Blueprint_CopperArmorCold_5",
     "Blueprint_IronArmorHeat_2",
     "Blueprint_IronArmorHeat_3",
     "Blueprint_IronArmorHeat_4",
     "Blueprint_IronArmorHeat_5",
     "Blueprint_IronArmorCold_2",
     "Blueprint_IronArmorCold_3",
     "Blueprint_IronArmorCold_4",
     "Blueprint_IronArmorCold_5",
     "Blueprint_StealArmorHeat_2",
     "Blueprint_StealArmorHeat_3",
     "Blueprint_StealArmorHeat_4",
     "Blueprint_StealArmorHeat_5",
     "Blueprint_StealArmorCold_2",
     "Blueprint_StealArmorCold_3",
     "Blueprint_StealArmorCold_4",
     "Blueprint_StealArmorCold_5",
     "Blueprint_FurHelmet_2",
     "Blueprint_FurHelmet_3",
     "Blueprint_FurHelmet_4",
     "Blueprint_FurHelmet_5",
     "Blueprint_CopperHelmet_2",
     "Blueprint_CopperHelmet_3",
     "Blueprint_CopperHelmet_4",
     "Blueprint_CopperHelmet_5",
     "Blueprint_IronHelmet_2",
     "Blueprint_IronHelmet_3",
     "Blueprint_IronHelmet_4",
     "Blueprint_IronHelmet_5",
     "Blueprint_StealHelmet_2",
     "Blueprint_StealHelmet_3",
     "Blueprint_StealHelmet_4",
     "Blueprint_StealHelmet_5",
     "Blueprint_Head001_1",
     "Blueprint_Head001_2",
     "Blueprint_Head001_3",
     "Blueprint_Head001_4",
     "Blueprint_Head001_5",
     "Blueprint_Head002_1",
     "Blueprint_Head002_2",
     "Blueprint_Head002_3",
     "Blueprint_Head002_4",
     "45264",
     "Blueprint_Head003_1",
     "Blueprint_Head003_2",
     "Blueprint_Head003_3",
     "Blueprint_Head003_4",
     "Blueprint_Head003_5",
     "Blueprint_Head004_1",
     "Blueprint_Head004_2",
     "Blueprint_Head004_3",
     "Blueprint_Head004_4",
     "Blueprint_Head004_5",
     "Blueprint_Head005_1",
     "Blueprint_Head005_2",
     "Blueprint_Head005_3",
     "Blueprint_Head005_4",
     "Blueprint_Head005_5",
     "Blueprint_Head006_1",
     "Blueprint_Head006_2",
     "Blueprint_Head006_3",
     "Blueprint_Head006_4",
     "Blueprint_Head006_5",
     "Blueprint_Head007_1",
     "Blueprint_Head007_2",
     "Blueprint_Head007_3",
     "Blueprint_Head007_4",
     "Blueprint_Head007_5",
     "Blueprint_Head008_1",
     "Blueprint_Head008_2",
     "Blueprint_Head008_3",
     "Blueprint_Head008_4",
     "Blueprint_Head008_5",
     "Blueprint_Head009_1",
     "Blueprint_Head009_2",
     "Blueprint_Head009_3",
     "Blueprint_Head009_4",
     "Blueprint_Head009_5",
     "Blueprint_Head010_1",
     "Blueprint_Head010_2",
     "Blueprint_Head010_3",
     "Blueprint_Head010_4",
     "Blueprint_Head010_5",
     "Blueprint_Head011_1",
     "Blueprint_Head011_2",
     "Blueprint_Head011_3",
     "Blueprint_Head011_4",
     "Blueprint_Head011_5",
     "Blueprint_Head012_1",
     "Blueprint_Head012_2",
     "Blueprint_Head012_3",
     "Blueprint_Head012_4",
     "Blueprint_Head012_5",
     "Blueprint_Head013_1",
     "Blueprint_Head013_2",
     "Blueprint_Head013_3",
     "Blueprint_Head013_4",
     "Blueprint_Head013_5",
     "Blueprint_Head014_1",
     "Blueprint_Head014_2",
     "Blueprint_Head014_3",
     "Blueprint_Head014_4",
     "Blueprint_Head014_5",
     "Blueprint_Head015_1",
     "Blueprint_Head015_2",
     "Blueprint_Head015_3",
     "Blueprint_Head015_4",
     "Blueprint_Head015_5",
     "Blueprint_Head016_1",
     "Blueprint_Head016_2",
     "Blueprint_Head016_3",
     "Blueprint_Head016_4",
     "Blueprint_Head016_5",
     "Blueprint_Head017_1",
     "Blueprint_Head017_2",
     "Blueprint_Head017_3",
     "Blueprint_Head017_4",
     "Blueprint_Head017_5",
     "Blueprint_WeakerBow_2",
     "Blueprint_WeakerBow_3",
     "Blueprint_WeakerBow_4",
     "Blueprint_WeakerBow_5",
     "Blueprint_BowGun_2",
     "Blueprint_BowGun_3",
     "Blueprint_BowGun_4",
     "Blueprint_BowGun_5",
     "Blueprint_AssaultRifle_Default2",
     "Blueprint_AssaultRifle_Default3",
     "Blueprint_AssaultRifle_Default4",
     "Blueprint_AssaultRifle_Default5",
     "Blueprint_PumpActionShotgun_2",
     "Blueprint_PumpActionShotgun_3",
     "Blueprint_PumpActionShotgun_4",
     "Blueprint_PumpActionShotgun_5",
     "Blueprint_HandGun_Default_2",
     "Blueprint_HandGun_Default_3",
     "Blueprint_HandGun_Default_4",
     "Blueprint_HandGun_Default_5",
     "Blueprint_Launcher_Default_2",
     "Blueprint_Launcher_Default_3",
     "Blueprint_Launcher_Default_4",
     "Blueprint_Launcher_Default_5",
     "ClothArmor_2",
     "ClothArmor_3",
     "ClothArmor_4",
     "ClothArmor_5",
     "FurArmor_2",
     "FurArmor_3",
     "FurArmor_4",
     "FurArmor_5",
     "CopperArmor_2",
     "CopperArmor_3",
     "CopperArmor_4",
     "CopperArmor_5",
     "IronArmor_2",
     "IronArmor_3",
     "IronArmor_4",
     "IronArmor_5",
     "StealArmor_2",
     "StealArmor_3",
     "StealArmor_4",
     "StealArmor_5",
     "Blueprint_ClothArmor_2",
     "Blueprint_ClothArmor_3",
     "Blueprint_ClothArmor_4",
     "Blueprint_ClothArmor_5",
     "Blueprint_FurArmor_2",
     "Blueprint_FurArmor_3",
     "Blueprint_FurArmor_4",
     "Blueprint_FurArmor_5",
     "Blueprint_CopperArmor_2",
     "Blueprint_CopperArmor_3",
     "Blueprint_CopperArmor_4",
     "Blueprint_CopperArmor_5",
     "Blueprint_IronArmor_2",
     "Blueprint_IronArmor_3",
     "Blueprint_IronArmor_4",
     "Blueprint_IronArmor_5",
     "Blueprint_StealArmor_2",
     "Blueprint_StealArmor_3",
     "Blueprint_StealArmor_4",
     "Blueprint_StealArmor_5",
     "Poppy",
     "Opium",
     "Narcotic",
     "StatusPointResetSan",
     "ClothArmorHeat",
     "ClothArmorCold",
     "FurArmorHeat",
     "FurArmorCold",
     "CopperArmorHeat",
     "CopperArmorCold",
     "IronArmorHeat",
     "IronArmorCold",
     "StealArmorHeat",
     "StealArmorCold",
     "Spear_QueenBee",
     "Spear_SoldierBee",
     "Spear_ForestBoss",
     "DecalGun_1",
     "DecalGun_2",
     "DecalGun_3",
     "DecalGun_4",
     "DecalGun_5",
     "InkBullet",
     "PalFluid",
     "Meat_ChickenPal",
     "Meat_SheepBall",
     "Meat_Kelpie",
     "Meat_Eagle",
     "Meat_Boar",
     "Meat_LazyCatfish",
     "Meat_Deer",
     "Meat_IceDeer",
     "Meat_BerryGoat",
     "Meat_CowPal",
     "Meat_SakuraSaurus",
     "Meat_GrassMammoth",
     "BakedMeat_ChickenPal",
     "BakedMeat_SheepBall",
     "BakedMeat_Kelpie",
     "BakedMeat_Eagle",
     "BakedMeat_Boar",
     "BakedMeat_LazyCatfish",
     "BakedMeat_Deer",
     "BakedMeat_IceDeer",
     "BakedMeat_BerryGoat",
     "BakedMeat_CowPal",
     "BakedMeat_SakuraSaurus",
     "BakedMeat_GrassMammoth",
     "ChickenSaute",
     "GrilledSheepHerbs",
     "GenghisKhan",
     "Eaglestew",
     "BaconEggs",
     "StewedIceDeer",
     "FriedChicken",
     "HotDog_2",
     "DeerLocoMoco",
     "DeerStew",
     "Hamburger_2",
     "Cheeseburger_2",
     "FriedKelpie",
     "Chowder",
    };
    /*static std::vector<std::string> db_pals =
    {
    "Alpaca",
    "AmaterasuWolf",
    "Anubis",
    "BadCatgirl",
    "Baphomet",
    "Baphomet_Dark",
    "Bastet",
    "Bastet_Ice",
    "BeardedDragon",
    "BerryGoat",
    "BirdDragon",
    "BirdDragon_Ice",
    "BlackCentaur",
    "BlackFurDragon",
    "BlackGriffon",
    "BlackMetalDragon",
    "BlueberryFairy",
    "BlueDragon",
    "BluePlatypus",
    "Boar",
    "BrownRabbit",
    "CaptainPenguin",
    "Carbunclo",
    "CatBat",
    "CatMage",
    "CatVampire",
    "ChickenPal",
    "ColorfulBird",
    "CowPal",
    "CuteButterfly",
    "CuteFox",
    "CuteMole",
    "DarkAlien",
    "DarkCrow",
    "DarkMechaDragon",
    "DarkMutant",
    "DarkScorpion",
    "Deer",
    "Deer_Ground",
    "DreamDemon",
    "DrillGame",
    "Eagle",
    "ElecCat",
    "ElecLion",
    "ElecPanda",
    "FairyDragon",
    "FairyDragon_Water",
    "FeatherOstrich",
    "FengyunDeeper",
    "FireKirin",
    "FireKirin_Dark",
    "FlameBambi",
    "FlameBuffalo",
    "FlowerDinosaur",
    "FlowerDinosaur_Electric",
    "FlowerDoll",
    "FlowerRabbit",
    "FlyingManta",
    "FoxMage",
    "Ganesha",
    "Garm",
    "GhostBeast",
    "GhostRabbit",
    "GoldenHorse",
    "Gorilla",
    "GrassDragon",
    "GrassMammoth",
    "GrassMammoth_Ice",
    "GrassPanda",
    "GrassPanda_Electric",
    "GrassRabbitMan",
    "GuardianDog",
    "HadesBird",
    "HawkBird",
    "Hedgehog",
    "Hedgehog_Ice",
    "HerculesBeetle",
    "Horus",
    "IceDeer",
    "IceFox",
    "IceHorse",
    "IceHorse_Dark",
    "JetDragon",
    "Kelpie",
    "Kelpie_Fire",
    "KingAlpaca",
    "KingAlpaca_Ice",
    "KingBahamut",
    "Kirin",
    "Kitsunebi",
    "LavaGirl",
    "LazyCatfish",
    "LazyDragon",
    "LazyDragon_Electric",
    "LeafPrincess",
    "LilyQueen",
    "LilyQueen_Dark",
    "LittleBriarRose",
    "LizardMan",
    "LizardMan_Fire",
    "Manticore",
    "Manticore_Dark",
    "Monkey",
    "MopBaby",
    "MopKing",
    "Mutant",
    "NaughtyCat",
    "NegativeKoala",
    "NegativeOctopus",
    "NightBlueHorse",
    "NightFox",
    "NightLady",
    "Penguin",
    "PinkCat",
    "PinkKangaroo",
    "PinkLizard",
    "PinkRabbit",
    "PlantSlime",
    "QueenBee",
    "RaijinDaughter",
    "RedArmorBird",
    "RobinHood",
    "RobinHood_Ground",
    "Ronin",
    "SaintCentaur",
    "SakuraSaurus",
    "SakuraSaurus_Water",
    "ScorpionMan",
    "Serpent",
    "Serpent_Ground",
    "SharkKid",
    "SharkKid_Fire",
    "SheepBall",
    "SifuDog",
    "SkyDragon",
    "SoldierBee",
    "Suzaku",
    "Suzaku_Water",
    "SweetsSheep",
    "TentacleTurtle",
    "ThunderBird",
    "ThunderDog",
    "ThunderDragonMan",
    "Umihebi",
    "Umihebi_Fire",
    "VioletFairy",
    "VolcanicMonster",
    "VolcanicMonster_Ice",
    "VolcanoDragon",
    "WaterLizard",
    "WeaselDragon",
    "Werewolf",
    "WhiteMoth",
    "WhiteTiger",
    "Windchimes",
    "Windchimes_Ice",
    "WingGolem",
    "WizardOwl",
    "WoolFox",
    "Yeti",
    "Yeti_Grass",
    "GrassBoss",
    "ForestBoss",
    "DessertBoss",
    "VolcanoBoss",
    "SnowBoss",
    };*/
    static std::string basic_items_stackable[15] =
    {
        "Wood",
        "Wool",
        "Stone",
        "ElectricOrgan",
        "Venom",
        "FireOrgan",
        "IceOrgan",
        "Bone",
        "Sand",
        "Silicon",
        "Cement",
        "CarbonFiber",
        "Horn",
        "Cake",
        "Cheeseburger_2"
    };

    static std::string basic_items_single[12] =
    {
        "AutoMealPouch_Tier5",
        "GrapplingGun_4",
        "BowGun_5",
        "StealArmor_5",
        "StealArmorCold_5",
        "StealArmorHeat_5",
        "StealHelmet_5",
        "HomingSphereLauncher",
        "Pickaxe_Tier_02",
        "Pickaxe_Tier_03",
        "Axe_Tier_02",
        "Axe_Tier_03",
    };

    static std::string tools[4] =
    {
        "Pickaxe_Tier_02",
        "Pickaxe_Tier_03",
        "Axe_Tier_02",
        "Axe_Tier_03",
    };

    static std::string pal_unlock_skills[90] =
    {
        "SkillUnlock_Alpaca",
        "SkillUnlock_AmaterasuWolf",
        "SkillUnlock_Anubis",
        "SkillUnlock_BadCatgirl",
        "SkillUnlock_BirdDragon",
        "SkillUnlock_BlackCentaur",
        "SkillUnlock_BlackFurDragon",
        "SkillUnlock_BlackGriffon",
        "SkillUnlock_BlackMetalDragon",
        "SkillUnlock_BlueDragon",
        "SkillUnlock_Boar",
        "SkillUnlock_CaptainPenguin",
        "SkillUnlock_Carbunclo",
        "SkillUnlock_ColorfulBird",
        "SkillUnlock_DarkMutant",
        "SkillUnlock_Deer",
        "SkillUnlock_DreamDemon",
        "SkillUnlock_DrillGame",
        "SkillUnlock_Eagle",
        "SkillUnlock_ElecLion",
        "SkillUnlock_ElecPanda",
        "SkillUnlock_FairyDragon",
        "SkillUnlock_FeatherOstrich",
        "SkillUnlock_FengyunDeeper",
        "SkillUnlock_FireKirin",
        "SkillUnlock_FlameBuffalo",
        "SkillUnlock_FlowerDinosaur",
        "SkillUnlock_FlowerRabbit",
        "SkillUnlock_FlyingManta",
        "SkillUnlock_Garm",
        "SkillUnlock_GhostBeast",
        "SkillUnlock_GoldenHorse",
        "SkillUnlock_GrassMammoth",
        "SkillUnlock_GrassPanda",
        "SkillUnlock_GuardianDog",
        "SkillUnlock_HadesBird",
        "SkillUnlock_HawkBird",
        "SkillUnlock_Hedgehog",
        "SkillUnlock_HerculesBeetle",
        "SkillUnlock_Horus",
        "SkillUnlock_IceDeer",
        "SkillUnlock_IceFox",
        "SkillUnlock_IceHorse",
        "SkillUnlock_JetDragon",
        "SkillUnlock_KingAlpaca",
        "SkillUnlock_KingBahamut",
        "SkillUnlock_Kirin",
        "SkillUnlock_Kitsunebi",
        "SkillUnlock_LazyDragon",
        "SkillUnlock_LilyQueen",
        "SkillUnlock_Manticore",
        "SkillUnlock_Monkey",
        "SkillUnlock_MopKing",
        "SkillUnlock_NaughtyCat",
        "SkillUnlock_NegativeOctopus",
        "SkillUnlock_Penguin",
        "SkillUnlock_RaijinDaughter",
        "SkillUnlock_RedArmorBird",
        "SkillUnlock_SaintCentaur",
        "SkillUnlock_SakuraSaurus",
        "SkillUnlock_Serpent",
        "SkillUnlock_SkyDragon",
        "SkillUnlock_Suzaku",
        "SkillUnlock_ThunderBird",
        "SkillUnlock_ThunderDog",
        "SkillUnlock_Umihebi",
        "SkillUnlock_VolcanicMonster",
        "SkillUnlock_WeaselDragon",
        "SkillUnlock_WingGolem",
        "SkillUnlock_WindChimes",
        "SkillUnlock_Yeti",
        "SkillUnlock_Umihebi_Fire",
        "SkillUnlock_Deer_Ground",
        "SkillUnlock_Hedgehog_Ice",
        "SkillUnlock_FlowerDinosaur_Electric",
        "SkillUnlock_GrassMammoth_Ice",
        "SkillUnlock_LazyDragon_Electric",
        "SkillUnlock_FireKirin_Dark",
        "SkillUnlock_SakuraSaurus_Water",
        "SkillUnlock_FairyDragon_Water",
        "SkillUnlock_Manticore_Dark",
        "SkillUnlock_Suzaku_Water",
        "SkillUnlock_Serpent_Ground",
        "SkillUnlock_VolcanicMonster_Ice",
        "SkillUnlock_IceHorse_Dark",
        "SkillUnlock_GrassPanda_Electric",
        "SkillUnlock_Yeti_Grass",
        "SkillUnlock_KingAlpaca_Ice",
        "SkillUnlock_BirdDragon_Ice",
        "SkillUnlock_WindChimes_Ice",
    };

    static std::string spheres[8] =
    {
        "PalSphere",
        "PalSphere_Giga",
        "PalSphere_Legend",
        "PalSphere_Master",
        "PalSphere_Mega",
        "PalSphere_Tera",
        "PalSphere_Robbery",
        "PalSphere_Debug",
    };

    const auto accessories =
    {
        "Accessory_AT_1|Attack Pendant",
        "Accessory_AT_2|Attack Pendant+1",
        "Accessory_AT_3|Attack Pendant+2",
        "Accessory_defense_1|Defense Pendant",
        "Accessory_defense_2|Defense Pendant +1",
        "Accessory_defense_3|Defense Pendant +2",
        "Accessory_HeatResist_1|Heat Resistant Underwear",
        "Accessory_HeatResist_2|Heat Resistant Underwear+1",
        "Accessory_HeatResist_3|Heat Resistant Underwear+2",
        "Accessory_HP_1|Life Pendant",
        "Accessory_HP_2|Life Pendant+1",
        "Accessory_HP_3|Life Pendant+2",
        "Accessory_WorkSpeed_1|Pendant Of Diligence",
        "Accessory_WorkSpeed_2|Pendant Of Diligence+1",
        "Accessory_WorkSpeed_3|Pendant Of Diligence+2",
        "Accessory_AquaResist_1|Ring Of Water Resistance",
        "Accessory_AquaResist_2|Ring Of Water Resistance+1",
        "Accessory_AquaResist_3|Ring Of Water Resistance+2",
        "Accessory_DarkResist_1|Ring Of Dark Resistance",
        "Accessory_DarkResist_2|Ring Of Dark Resistance+1",
        "Accessory_DarkResist_3|Ring Of Dark Resistance+2",
        "Accessory_DragonResist_1|Ring Of Dragon Resistance",
        "Accessory_DragonResist_2|Ring Of Dragon Resistance+1",
        "Accessory_DragonResist_3|Ring Of Dragon Resistance+2",
        "Accessory_EarthResist_1|Ring Of Earth Resistance",
        "Accessory_EarthResist_2|Ring Of Earth Resistance+1",
        "Accessory_EarthResist_3|Ring Of Earth Resistance+2",
        "Accessory_FireResist_1|Ring Of Flame Resistance",
        "Accessory_FireResist_2|Ring Of Flame Resistance+1",
        "Accessory_FireResist_3|Ring Of Flame Resistance+2",
        "Accessory_IceResist_1|Ring Of Ice Resistance",
        "Accessory_IceResist_2|Ring Of Ice Resistance+1",
        "Accessory_IceResist_3|Ring Of Ice Resistance+2",
        "Accessory_LeafResist_1|Ring Of Grass Resistance",
        "Accessory_LeafResist_2|Ring Of Grass Resistance+1",
        "Accessory_LeafResist_3|Ring Of Grass Resistance+2",
        "Accessory_NormalResist_1|Ring Of Resistance",
        "Accessory_NormalResist_2|Ring Of Resistance+1",
        "Accessory_NormalResist_3|Ring Of Resistance+2",
        "Accessory_ThunderResist_1|Ring Of Lightning Resistance",
        "Accessory_ThunderResist_2|Ring Of Lightning Resistance+1",
        "Accessory_ThunderResist_3|Ring Of Lightning Resistance+2",
        "Accessory_CoolResist_1|Thermal Underwear",
        "Accessory_CoolResist_2|Thermal Underwear+1",
        "Accessory_CoolResist_3|Thermal Underwear+2"
    };

    const auto ammo =
    {
        "AssaultRifleBullet|Assault Rifle Ammo",
        "Arrow|Arrow",
        "RoughBullet|Coarse Ammo",
        "InkBullet|Decal Ink",
        "Arrow_Fire|Fire Arrow",
        "HandgunBullet|Handgun Ammo",
        "LaserBullet|Laser Ammo",
        "MachingunBullet|Machine Gun Ammo",
        "MagnumBullet|Magnum Ammo",
        "Arrow_Poison|Poison Arrow",
        "ExplosiveBullet|Rocket Ammo",
        "RifleBullet|Rifle Ammo",
        "ShotgunBullet|Shotgun Shells"
    };

    const auto armor =
    {
        "AutoMealPouch_Tier2|Average Feed Bag",
        "ClothArmor|Cloth Outfit(Common)",
        "ClothArmor_2|Cloth Outfit(Uncommon)",
        "ClothArmor_3|Cloth Outfit(Rare)",
        "ClothArmor_4|Cloth Outfit(Epic)",
        "ClothArmor_5|Cloth Outfit(Legendary)",
        "CopperArmorCold|Cold Resistant Metal Armor(Common)",
        "CopperArmorCold_2|Cold Resistant Metal Armor(Uncommon)",
        "CopperArmorCold_3|Cold Resistant Metal Armor(Rare)",
        "CopperArmorCold_4|Cold Resistant Metal Armor(Epic)",
        "CopperArmorCold_5|Cold Resistant Metal Armor(Legendary)",
        "FurArmorCold|Cold Resistant Pelt Armor(Common)",
        "FurArmorCold_2|Cold Resistant Pelt Armor(Uncommon)",
        "FurArmorCold_3|Cold Resistant Pelt Armor(Rare)",
        "FurArmorCold_4|Cold Resistant Pelt Armor(Epic)",
        "FurArmorCold_5|Cold Resistant Pelt Armor(Legendary)",
        "IronArmorCold|Cold Resistant Refined Metal Armor(Common)",
        "IronArmorCold_2|Cold Resistant Refined Metal Armor(Uncommon)",
        "IronArmorCold_3|Cold Resistant Refined Metal Armor(Rare)",
        "IronArmorCold_4|Cold Resistant Refined Metal Armor(Epic)",
        "IronArmorCold_5|Cold Resistant Refined Metal Armor(Legendary)",
        "StealArmorCold|Cold Resistant Pal Metal Armor(Common)",
        "StealArmorCold_2|Cold Resistant Pal Metal Armor(Uncommon)",
        "StealArmorCold_3|Cold Resistant Pal Metal Armor(Rare)",
        "StealArmorCold_4|Cold Resistant Pal Metal Armor(Epic)",
        "StealArmorCold_5|Cold Resistant Pal Metal Armor(Legendary)",
        "FurHelmet|Feathered Hair Band(Common)",
        "FurHelmet_2|Feathered Hair Band(Uncommon)",
        "FurHelmet_3|Feathered Hair Band(Rare)",
        "FurHelmet_4|Feathered Hair Band(Epic)",
        "FurHelmet_5|Feathered Hair Band(Legendary)",
        "AutoMealPouch_Tier5|Giant Feed Bag",
        "CopperArmorHeat|Heat Resistant Metal Armor(Common)",
        "CopperArmorHeat_2|Heat Resistant Metal Armor(Uncommon)",
        "CopperArmorHeat_3|Heat Resistant Metal Armor(Rare)",
        "CopperArmorHeat_4|Heat Resistant Metal Armor(Epic)",
        "CopperArmorHeat_5|Heat Resistant Metal Armor(Legendary)",
        "FurArmorHeat|Heat Resistant Pelt Armor(Common)",
        "FurArmorHeat_2|Heat Resistant Pelt Armor(Uncommon)",
        "FurArmorHeat_3|Heat Resistant Pelt Armor(Rare)",
        "FurArmorHeat_4|Heat Resistant Pelt Armor(Epic)",
        "FurArmorHeat_5|Heat Resistant Pelt Armor(Legendary)",
        "AutoMealPouch_Tier4|Huge Feed Bag",
        "IronArmorHeat|Heat Resistant Refined Metal Armor(Common)",
        "IronArmorHeat_2|Heat Resistant Refined Metal Armor(Uncommon)",
        "IronArmorHeat_3|Heat Resistant Refined Metal Armor(Rare)",
        "IronArmorHeat_4|Heat Resistant Refined Metal Armor(Epic)",
        "IronArmorHeat_5|Heat Resistant Refined Metal Armor(Legendary)",
        "StealArmorHeat|Heat Resistant Pal Metal Armor(Common)",
        "StealArmorHeat_2|Heat Resistant Pal Metal Armor(Uncommon)",
        "StealArmorHeat_3|Heat Resistant Pal Metal Armor(Rare)",
        "StealArmorHeat_4|Heat Resistant Pal Metal Armor(Epic)",
        "StealArmorHeat_5|Heat Resistant Pal Metal Armor(Legendary)",
        "AutoMealPouch_Tier3|Large Feed Bag",
        "CopperArmor|Metal Armor(Common)",
        "CopperArmor_2|Metal Armor(Uncommon)",
        "CopperArmor_3|Metal Armor(Rare)",
        "CopperArmor_4|Metal Armor(Epic)",
        "CopperArmor_5|Metal Armor(Legendary)",
        "CopperHelmet|Metal Helm(Common)",
        "CopperHelmet_2|Metal Helm(Uncommon)",
        "CopperHelmet_3|Metal Helm(Rare)",
        "CopperHelmet_4|Metal Helm(Epic)",
        "CopperHelmet_5|Metal Helm(Legendary)",
        "FurArmor|Pelt Armor(Common)",
        "FurArmor_2|Pelt Armor(Uncommon)",
        "FurArmor_3|Pelt Armor(Rare)",
        "FurArmor_4|Pelt Armor(Epic)",
        "FurArmor_5|Pelt Armor(Legendary)",
        "StealArmor|Pal Metal Armor(Common)",
        "StealArmor_2|Pal Metal Armor(Uncommon)",
        "StealArmor_3|Pal Metal Armor(Rare)",
        "StealArmor_4|Pal Metal Armor(Epic)",
        "StealArmor_5|Pal Metal Armor(Legendary)",
        "StealHelmet|Pal Metal Helm(Common)",
        "StealHelmet_2|Pal Metal Helm(Uncommon)",
        "StealHelmet_3|Pal Metal Helm(Rare)",
        "StealHelmet_4|Pal Metal Helm(Epic)",
        "StealHelmet_5|Pal Metal Helm(Legendary)",
        "IronArmor|Refined Metal Armor(Common)",
        "IronArmor_2|Refined Metal Armor(Uncommon)",
        "IronArmor_3|Refined Metal Armor(Rare)",
        "IronArmor_4|Refined Metal Armor(Epic)",
        "IronArmor_5|Refined Metal Armor(Legendary)",
        "IronHelmet|Refined Metal Helm(Common)",
        "IronHelmet_2|Refined Metal Helm(Uncommon)",
        "IronHelmet_3|Refined Metal Helm(Rare)",
        "IronHelmet_4|Refined Metal Helm(Epic)",
        "IronHelmet_5|Refined Metal Helm(Legendary)",
        "AutoMealPouch_Tier1|Small Feed Bag",
        "ClothArmorCold|Tundra Outfit(Common)",
        "ClothArmorCold_2|Tundra Outfit(Uncommon)",
        "ClothArmorCold_3|Tundra Outfit(Rare)",
        "ClothArmorCold_4|Tundra Outfit(Epic)",
        "ClothArmorCold_5|Tundra Outfit(Legendary)",
        "ClothArmorHeat|Tropical Outfit(Common)",
        "ClothArmorHeat_2|Tropical Outfit(Uncommon)",
        "ClothArmorHeat_3|Tropical Outfit(Rare)",
        "ClothArmorHeat_4|Tropical Outfit(Epic)",
        "ClothArmorHeat_5|Tropical Outfit(Legendary)",
    };

    const auto craftingmaterials =
    {
        "PalCrystal_Ex|Ancient Civilization Parts",
        "Bone|Bone",
        "Poppy|Beautiful Flowers",
        "CrudeOil|Crude Oil",
        "Claws|Claws",
        "Cloth|Cloth",
        "Coal|Coal",
        "Cement|Cement",
        "Charcoal|Charcoal",
        "CarbonFiber|Carbon Fiber",
        "MachineParts2|Circuit Board",
        "ElectricOrgan|Electric Organ",
        "Flour|Flour",
        "Fiber|Fiber",
        "FireOrgan|Flame Organ",
        "GunPowder2|Gunpowder",
        "PalItem_PlantSlime|Gumoss Leaf",
        "Cloth2|High Quality Cloth",
        "PalOil|High Quality Pal Oil",
        "Horn|Horn",
        "CopperIngot|Ingot",
        "IceOrgan|Ice Organ",
        "PalItem_CatMage|Katress Hair",
        "Leather|Leather",
        "MachineParts|Nails",
        "CopperOre|Ore",
        "PalFluid|Pal Fluids",
        "Polymer|Polymer",
        "Pal_crystal_L|Paldium Clump",
        "Pal_crystal_S|Paldium Fragment",
        "StealIngot|Pal Metal Ingot",
        "Quartz|Pure Quartz",
        "PalItem_CaptainPenguin|Punking Plume",
        "IronIngot|Refined Ingot",
        "Stone|Stone",
        "Sulfur|Sulfur",
        "PalItem_ColorfulBird|Tocotoco Feather",
        "Venom|Venom Gland",
        "Wood|Wood",
        "Wool|Wool"
    };

    const auto eggs =
    {
        "PalEgg_Dark_01|Dark Egg",
        "PalEgg_Dark_02|Dark Egg(2)",
        "PalEgg_Dark_03|Large Dark Egg",
        "PalEgg_Dark_04|Large Dark Egg(2)",
        "PalEgg_Dark_05|Huge Dark Egg",
        "PalEgg_Dragon_01|Dragon Egg",
        "PalEgg_Dragon_02|Dragon Egg(2)",
        "PalEgg_Dragon_03|Large Dragon Egg",
        "PalEgg_Dragon_04|Large Dragon Egg(2)",
        "PalEgg_Dragon_05|Huge Dragon Egg",
        "PalEgg_Earth_01|Rocky Egg",
        "PalEgg_Earth_02|Rough Egg(2)",
        "PalEgg_Earth_03|Large Rocky Egg",
        "PalEgg_Earth_04|Large Rocky Egg(2)",
        "PalEgg_Earth_05|Huge Rocky Egg",
        "PalEgg_Electricity_01|Electric Egg",
        "PalEgg_Electricity_02|Electric Egg(2)",
        "PalEgg_Electricity_03|Large Electric Egg",
        "PalEgg_Electricity_04|Large Electric Egg(2)",
        "PalEgg_Electricity_05|Huge Electric Egg",
        "PalEgg_Fire_01|Scorching Egg",
        "PalEgg_Fire_02|Scorching Egg(2)",
        "PalEgg_Fire_03|Large Scorching Egg",
        "PalEgg_Fire_04|Large Scorching Egg",
        "PalEgg_Fire_05|Huge Scorching Egg",
        "PalEgg_Ice_01|Frozen Egg",
        "PalEgg_Ice_02|Frozen Egg(2)",
        "PalEgg_Ice_03|Large Frozen Egg",
        "PalEgg_Ice_04|Large Frozen Egg(2)",
        "PalEgg_Ice_05|Huge Frozen Egg",
        "PalEgg_Leaf_01|Verdant Egg",
        "PalEgg_Leaf_02|Verdant Egg(2)",
        "PalEgg_Leaf_03|Large Verdant Egg",
        "PalEgg_Leaf_04|Large Verdant Egg(2)",
        "PalEgg_Leaf_05|Huge Verdant Egg",
        "PalEgg_Normal_01|Common Egg",
        "PalEgg_Normal_02|Common Egg(2)",
        "PalEgg_Normal_03|Large Common Egg",
        "PalEgg_Normal_04|Large Common Egg(2)",
        "PalEgg_Normal_05|Huge Common Egg",
        "PalEgg_Water_01|Damp Egg",
        "PalEgg_Water_02|Damp Egg(2)",
        "PalEgg_Water_03|Large Damp Egg",
        "PalEgg_Water_04|Large Damp Egg(2)",
        "PalEgg_Water_05|Huge Damp Egg"
    };

    const auto food =
    {
        "BLT|Burrito",
        "BakedMeat_LazyCatfish|Broiled Dumund",
        "BakedMeat_SakuraSaurus|Broncherry Rib Roast",
        "BakedMushroom|Baked Mushrooms",
        "Baked_Berries|Baked Berries",
        "MeatSauce|Bolognese Sauce",
        "Meat_SakuraSaurus|Broncherry Meat",
        "Pan|Bread",
        "Cake|Cake",
        "CheeseBurger|Cheeseburger",
        "ChickenSaute|Chikipi Sauté",
        "Carbonara|Carbonara",
        "Meat_BerryGoat|Caprity Meat",
        "Meat_ChickenPal|Chikipi Poultry",
        "CornSoup|Corn Soup",
        "Sweet|Cotton Candy",
        "Chowder|Dumund Chowder",
        "Egg|Egg",
        "DeerLocoMoco|Eikthyrdeer Loco Moco",
        "DeerStew|Eikthyrdeer Stew",
        "Meat_Deer|Eikthyrdeer Venison",
        "FriedChicken|Fried Chikipi",
        "FriedEggs|Fried Eggs",
        "FriedKelpie|Fried Kepsea",
        "BakedMeat_ChickenPal|Grilled Chikipi",
        "BakedMeat_Eagle|Grilled Galeclaw",
        "BakedMeat_Kelpie|Grilled Kelpsea",
        "Meat_Eagle|Galeclaw Poultry",
        "GrilledMeat|Grilled Meat",
        "GenghisKhan|Grilled Lamball",
        "BakedMeat_BerryGoat|Herb Roasted Caprity",
        "Honey|Honey",
        "HotDog|Hot Dog",
        "HotMilk|Hot Milk",
        "GrilledSheepHerbs|Herb Roasted Lamball",
        "Hamburger|Hamburger",
        "JamBun|Jam-filled Bun",
        "BakedMeat_SheepBall|Lamball Kebab",
        "Meat_SheepBall|Lamball Mutton",
        "Lettuce|Lettuce",
        "BakedMeat_CowPal|Moazzarina Steak",
        "BakedMeat_GrassMammoth|Mammorest Steak",
        "CheeseBurger_2|Mozzarina Cheeseburger",
        "Meat_CowPal|Mozzarina Meat",
        "Meat_GrassMammoth|Mammorest Meat",
        "Hamburger_2|Mozzarina Hamburger",
        "Milk|Milk",
        "MarinatedMushrooms|Marinated Mushrooms",
        "MushroomSoup|Mushroom Soup",
        "Mushroom|Mushroom",
        "Omelet|Omelet",
        "Pancake|Pancake",
        "Pizza|Pizza",
        "BaconEggs|Rushoar Bacon 'n' Eggs",
        "BakedMeat_Boar|Roast Rushoar",
        "BakedMeat_Deer|Roast Eikthyrdeer",
        "BakedMeat_IceDeer|Roast Reindrix",
        "Meat_Boar|Roshoar Pork",
        "Meat_IceDeer|Reindrix Venison",
        "Meat_Kelpie|Raw Kelpsea",
        "Meat_LazyCatfish|Raw Dumund",
        "Meat|Raw Meat",
        "HotDog_2|Rushoar Hot Dog",
        "StewedIceDeer|Reindrix Stew",
        "Berries|Red Wild Berries",
        "Eaglestew|Stewed Galeclaw",
        "FriedVegetables|Stir-fried Veggies",
        "Salad|Salad",
        "MushroomStew|Stewed Mushrooms",
        "Tomato|Tomato",
        "Wheat|Wheat"
    };

    const auto hats =
    {
        "Head012|Bowler Hat(Common)",
        "Head012_2|Bowler Hat(Uncommon)",
        "Head012_3|Bowler Hat(Rare)",
        "Head012_4|Bowler Hat(Epic)",
        "Head012_5|Bowler Hat(Legendary)",
        "Head009|Explorer Cap(Common)",
        "Head009_2|Explorer Cap(Uncommon)",
        "Head009_3|Explorer Cap(Rare)",
        "Head009_4|Explorer Cap(Epic)",
        "Head009_5|Explorer Cap(Legendary)",
        "Head011|Farming Hat(Common)",
        "Head011_2|Farming Hat(Uncommon)",
        "Head011_3|Farming Hat(Rare)",
        "Head011_4|Farming Hat(Epic)",
        "Head011_5|Farming Hat(Legendary)",
        "Head002|Golden Crown(Common)",
        "Head002_2|Golden Crown(Uncommon)",
        "Head002_3|Golden Crown(Rare)",
        "Head002_4|Golden Crown(Epic)",
        "Head002_5|Golden Crown(Legendary)",
        "Head010|Graduation Cap(Common)",
        "Head010_2|Graduation Cap(Uncommon)",
        "Head010_3|Graduation Cap(Rare)",
        "Head010_4|Graduation Cap(Epic)",
        "Head010_5|Graduation Cap(Legendary)",
        "Head014|Grinning Tocotoco Cap(Common)",
        "Head014_2|Grinning Tocotoco Cap(Uncommon)",
        "Head014_3|Grinning Tocotoco Cap(Rare)",
        "Head014_4|Grinning Tocotoco Cap(Epic)",
        "Head014_5|Grinning Tocotoco Cap(Legendary)",
        "Head015|Gusmoss Cap(Common)",
        "Head015_2|Gusmoss Cap(Uncommon)",
        "Head015_3|Gusmoss Cap(Rare)",
        "Head015_4|Gusmoss Cap(Epic)",
        "Head015_5|Gusmoss Cap(Legendary)",
        "Head006|Helmet(Common)",
        "Head006_2|Helmet(Uncommon)",
        "Head006_3|Helmet(Rare)",
        "Head006_4|Helmet(Epic)",
        "Head006_5|Helmet(Legendary)",
        "Head017|Katress Cap(Common)",
        "Head017_2|Katress Cap(Uncommon)",
        "Head017_3|Katress Cap(Rare)",
        "Head017_4|Katress Cap(Epic)",
        "Head017_5|Katress Cap(Legendary)",
        "Head003|Long-eared Headband(Common)",
        "Head003_2|Long-eared Headband(Uncommon)",
        "Head003_3|Long-eared Headband(Rare)",
        "Head003_4|Long-eared Headband(Epic)",
        "Head003_5|Long-eared Headband(Legendary)",
        "Head001|Monarch's Crown(Common)",
        "Head001_2|Monarch's Crown(Uncommon)",
        "Head001_3|Monarch's Crown(Rare)",
        "Head001_4|Monarch's Crown(Epic)",
        "Head001_5|Monarch's Crown(Legendary)",
        "Head016|Penking Cap(Common)",
        "Head016_2|Penking Cap(Uncommon)",
        "Head016_3|Penking Cap(Rare)",
        "Head016_4|Penking Cap(Epic)",
        "Head016_5|Penking Cap(Legendary)",
        "Head005|Soft Hat(Common)",
        "Head005_2|Soft Hat(Uncommon)",
        "Head005_3|Soft Hat(Rare)",
        "Head005_4|Soft Hat(Epic)",
        "Head005_5|Soft Hat(Legendary)",
        "Head007|Silk Hat(Common)",
        "Head007_2|Silk Hat(Uncommon)",
        "Head007_3|Silk Hat(Rare)",
        "Head007_4|Silk Hat(Epic)",
        "Head007_5|Silk Hat(Legendary)",
        "Head008|Tricorne(Common)",
        "Head008_2|Tricorne(Uncommon)",
        "Head008_3|Tricorne(Rare)",
        "Head008_4|Tricorne(Epic)",
        "Head008_5|Tricorne(Legendary)",
        "Head013|Tocotoco Cap(Common)",
        "Head013_2|Tocotoco Cap(Uncommon)",
        "Head013_3|Tocotoco Cap(Rare)",
        "Head013_4|Tocotoco Cap(Epic)",
        "Head013_5|Tocotoco Cap(Legendary)",
        "Head004|Witch Hat(Common)",
        "Head004_2|Witch Hat(Uncommon)",
        "Head004_3|Witch Hat(Rare)",
        "Head004_4|Witch Hat(Epic)",
        "Head004_5|Witch Hat(Legendary)"
    };

    const auto medicine =
    {
        "LuxuryMedicines|High Grade Medical Supplies",
        "Herbs|Low Quality Medical Supplies",
        "Medicines|Medical Supplies",
        "MindControlDrug|Mind Control Meds",
        "StatusPointResetSan|Memory Wiping Medicine",
        "Narcotic|Strange Juice",
        "Opium|Suspicious Juice"
    };

    const auto other =
    {
        "Unko_S|Dung",
        "TechnologyBook_G3|Future Technical Manual",
        "TechnologyBook_G1|High Grade Technical Manual",
        "Unko_L|Huge Dung Pile",
        "TechnologyBook_G2|Innovative Technical Manual",
        "PalUpgradeStone3|Large Pal Soul",
        "Relic|Lifmunk Effigy",
        "PalUpgradeStone2|Medium Pal Soul",
        "PalItem_ToSell_01|Precious Dragon Stone",
        "PalItem_ToSell_02|Precious Plume",
        "PalItem_ToSell_03|Precious Entrails",
        "PalItem_ToSell_04|Precious Claw",
        "PalItem_ToSell_05|Precious Pelt",
        "PalUpgradeStone|Small Pal Soul"
    };

    const auto palspheres =
    {
        "PalSphere_Giga|Giga Sphere",
        "PalSphere_Tera|Hyper Sphere",
        "PalSphere_Legend|Legendary Sphere",
        "PalSphere_Mega|Mega Sphere",
        "PalSphere|Pal Sphere",
        "PalSphere_Robbery|Radar Sphere",
        "PalSphere_Master|Ultra Sphere",
        "PalSphere_Debug|Debug Sphere"
    };
    const auto saddles =
    {
        "SkillUnlock_Boar|Rushoar Saddle",
     "SkillUnlock_CaptainPenguin|Captain Penguin Saddle",
     "SkillUnlock_Carbunclo|Lifmunk Saddle",
     "SkillUnlock_ColorfulBird|Tocotoco Saddle",
     "SkillUnlock_DarkMutant|Dark Mutant Saddle",
     "SkillUnlock_Deer|Eikthyrdeer Saddle",
     "SkillUnlock_DreamDemon|Daedream Saddle",
     "SkillUnlock_DrillGame|Digtoise Saddle",
     "SkillUnlock_Eagle|Galeclaw Saddle",
     "SkillUnlock_ElecLion|Boltmane Saddle",
     "SkillUnlock_ElecPanda|Grizzbolt Saddle",
     "SkillUnlock_FairyDragon|Elphidran Saddle",
     "SkillUnlock_FeatherOstrich|Feather Ostrich Saddle",
     "SkillUnlock_FengyunDeeper|Fenglope Saddle",
     "SkillUnlock_FireKirin|Pyrin Saddle",
     "SkillUnlock_FlameBuffalo|Arsox Saddle",
     "SkillUnlock_FlowerDinosaur|Dinossom Saddle",
     "SkillUnlock_FlowerRabbit|Flopie Saddle",
     "SkillUnlock_FlyingManta|Celaray Saddle",
     "SkillUnlock_Garm|Direhowl Saddle",
     "SkillUnlock_GhostBeast|Maraith Saddle",
     "SkillUnlock_GoldenHorse|Golden Horse Saddle",
     "SkillUnlock_GrassMammoth|Mammorest Saddle",
     "SkillUnlock_GrassPanda|Mossanda Saddle",
     "SkillUnlock_GuardianDog|Guardian Dog Saddle",
     "SkillUnlock_HadesBird|Helzypher Saddle",
     "SkillUnlock_HawkBird|Nitewing Saddle",
     "SkillUnlock_Hedgehog|Jolthog Saddle",
     "SkillUnlock_HerculesBeetle|Hercules Beetle Saddle",
     "SkillUnlock_Horus|Faleris Saddle",
     "SkillUnlock_IceDeer|Reindrix Saddle",
     "SkillUnlock_IceFox|Ice Fox Saddle",
     "SkillUnlock_IceHorse|Frostallion Saddle",
     "SkillUnlock_JetDragon|Jetragon Saddle",
     "SkillUnlock_KingAlpaca|Kingpaca Saddle",
     "SkillUnlock_KingBahamut|Blazamut Saddle",
     "SkillUnlock_Kirin|Univolt Saddle",
     "SkillUnlock_Kitsunebi|Foxpark Saddle",
     "SkillUnlock_LazyDragon|Relaxaurus Saddle",
     "SkillUnlock_LilyQueen|Lily Queen Saddle",
     "SkillUnlock_Manticore|Blazehowl Saddle",
     "SkillUnlock_Monkey|Tanzee Saddle",
     "SkillUnlock_MopKing|Sweepa Saddle",
     "SkillUnlock_NaughtyCat|Grintale saddle",
     "SkillUnlock_NegativeOctopus|Killamari Saddle",
     "SkillUnlock_Penguin|Pengullet Saddle",
     "SkillUnlock_RaijinDaughter|Dazzi Saddle",
     "SkillUnlock_RedArmorBird|Ragnahawk Saddle",
     "SkillUnlock_SaintCentaur|Paladius Saddle",
     "SkillUnlock_SakuraSaurus|Broncherry Saddle",
     "SkillUnlock_Serpent|Surfent Saddle",
     "SkillUnlock_SkyDragon|Quivern Saddle",
     "SkillUnlock_Suzaku|Suzaku Saddle",
     "SkillUnlock_ThunderBird|Breakon Saddle",
     "SkillUnlock_ThunderDog|Rayhound Saddle",
     "SkillUnlock_Umihebi|Jormuntide Saddle",
     "SkillUnlock_VolcanicMonster|Reptyro Saddle",
     "SkillUnlock_WeaselDragon|Chillet Saddle",
     "SkillUnlock_WingGolem|Wing Golem Saddle",
     "SkillUnlock_WindChimes|Hangyu Saddle",
     "SkillUnlock_Yeti|Wumpo Saddle",
     "SkillUnlock_Umihebi_Fire|Jormuntide Ignis Saddle",
     "SkillUnlock_Deer_Ground|Eikthyrdeer Terra Saddle",
     "SkillUnlock_Hedgehog_Ice|Jolthog Cryst Saddle",
     "SkillUnlock_FlowerDinosaur_Electric|Dinossom Lux Saddle",
     "SkillUnlock_GrassMammoth_Ice|Mammorest Cryst Saddle",
     "SkillUnlock_LazyDragon_Electric|Relaxaurus Lux Saddle",
     "SkillUnlock_FireKirin_Dark|Dark Pyrin Saddle",
     "SkillUnlock_SakuraSaurus_Water|Water Broncherry Saddle",
     "SkillUnlock_FairyDragon_Water|Water Elphidran Saddle",
     "SkillUnlock_Manticore_Dark|Dark Kingferno Saddle",
     "SkillUnlock_Suzaku_Water|Water Suzaku Saddle",
     "SkillUnlock_Serpent_Ground|Aquadon Terra Saddle",
     "SkillUnlock_VolcanicMonster_Ice|Ice Reptyro Saddle",
     "SkillUnlock_IceHorse_Dark|Frostallion Noct Saddle",
     "SkillUnlock_GrassPanda_Electric|Mossanda Lux Saddle",
     "SkillUnlock_Yeti_Grass|Wumpo Botan",
     "SkillUnlock_KingAlpaca_Ice|Kingpaca",
     "SkillUnlock_BirdDragon_Ice|Vanwyrm Cryst",
     "SkillUnlock_WindChimes_Ice|Hangyu Cryst Saddle",
    };
    const auto seeds =
    {
        "BerrySeeds|Berry Seeds",
        "LettuceSeeds|Lettuce Seeds",
        "TomatoSeeds|Tomato Seeds",
        "WheatSeeds|Wheat Seeds",
    };

    const auto toolss =
    {
        "Shield_01|Common Shield",
        "TreasureBoxKey01|Copper Key",
        "Glider_Super|Giga Glider",
        "Shield_03|Giga Shield",
        "TreasureBoxKey03|Golden Key",
        "Glider_Legendary|HyperGlider",
        "Lantern|Hip Lantern",
        "Shield_04|HyperShield",
        "Torch|Hand-held Torch",
        "Axe_Tier_01|Metal Ax",
        "Pickaxe_Tier_01|Metal Pickaxe",
        "Glider_Good|Mega Glider",
        "Shield_02|Mega Shield",
        "MeatCutterKnife|Meat Cleaver",
        "Glider_Old|Normal Parachute",
        "Axe_Tier_02|Refined Metal Ax",
        "Pickaxe_Tier_02|Refined Metal Pickaxe",
        "RepairKit|Repair Kit",
        "Axe_Tier_00|Stone Ax",
        "Pickaxe_Tier_00|Stone Pickaxe",
        "TreasureBoxKey02|Silver Key"
    };

    const auto weapons =
    {
        "AssaultRifle_Default1|Assault Rifle(Common)",
        "AssaultRifle_Default2|Assault Rifle(Uncommon)",
        "AssaultRifle_Default3|Assault Rifle(Rare)",
        "AssaultRifle_Default4|Assault Rifle(Epic)",
        "AssaultRifle_Default5|Assault Rifle(Legendary)",
        "Bat2|Bat",
        "Spear_SoldierBee|Beegarde's Spear",
        "BowGun|Crossbow(Common)",
        "BowGun_2|Crossbow(Uncommon)",
        "BowGun_3|Crossbow(Rare)",
        "BowGun_4|Crossbow(Epic)",
        "BowGun_5|Crossbow(Legendary)",
        "DecalGun_1|Decal Gun 1",
        "DecalGun_2|Decal Gun 2",
        "DecalGun_3|Decal Gun 3",
        "DecalGun_4|Decal Gun 4",
        "DecalGun_5|Decal Gun 5",
        "DoubleBarrelShotgun|Double-barreled Shotgun",
        "Spear_QueenBee|Elizabee's Staff",
        "BowGun_Fire|Fire Arrow Crossbow",
        "Bow_Fifth|Five Shot Bow",
        "Bow_Fire|Fire Bow",
        "FragGrenade|Frag Grenade",
        "GrapplingGun|Grappling Gun",
        "GrapplingGun2|Mega Grappling Gun",
        "GrapplingGun3|Giga Grappling Gun",
        "GrapplingGun4|Hyper Grappling Gun",
        "HomingSphereLauncher|Homing Sphere Launcher",
        "FragGrenade_Fire|Incendiary Grenade",
        "FragGrenade_Ice|Ice Grenade",
        "MakeshiftHandgun|Inferior Handgun",
        "LaserRifle|Laser Rifle",
        "Spear_ForestBoss|Lily's Spear",
        "Musket|Musket",
        "Spear_2|Metal Spear",
        "WeakerBow|Old Bow(Common)",
        "WeakerBow_2|Old Bow(Uncommon)",
        "WeakerBow_3|Old Bow(Rare)",
        "WeakerBow_4|Old Bow(Epic)",
        "WeakerBow_5|Old Bow(Legendary)",
        "BowGun_Poison|Poison Arrow Crossbow",
        "Bow_Poison|Poison Bow",
        "HandGun_Default|Pistol(Common)",
        "HandGun_Default_2|Pistol(Uncommon)",
        "HandGun_Default_3|Pistol(Rare)",
        "HandGun_Default_4|Pistol(Epic)",
        "HandGun_Default_5|Pistol(Legendary)",
        "PumpActionShotgun|Pump Action Shotgun(Common)",
        "PumpActionShotgun_2|Pump Action Shotgun(Uncommon)",
        "PumpActionShotgun_3|Pump Action Shotgun(Rare)",
        "PumpActionShotgun_4|Pump Action Shotgun(Epic)",
        "PumpActionShotgun_5|Pump Action Shotgun(Legendary)",
        "Launcher_Default|Rocket Launcher(Common)",
        "Launcher_Default_2|Rocket Launcher(Uncommon)",
        "Launcher_Default_3|Rocket Launcher(Rare)",
        "Launcher_Default_4|Rocket Launcher(Epic)",
        "Launcher_Default_5|Rocket Launcher(Legendary)",
        "RecurveBow|RecurveBow",
        "Spear_3|Refined Metal Spear",
        "FragGrenade_Elec|Shock Grenade",
        "ElecBaton|Stun Baton",
        "SingleShotRifle|Single-shot Rifle",
        "SniperRifle_Default|Sniper Rifle",
        "Spear|Stone Spear",
        "SphereLauncher|Scatter Sphere Launcher",
        "SphereLauncher_Once|Single-shot Sphere Launcher",
        "Sword|Sword",
        "Bow_triple|Triple Shot Bow",
        "Bat|Wooden Club",
    };

    const auto money =
    {
        "Diamond|Diamond",
        "Eemerald|Emerald",
        "Money|Gold Coin",
        "Quartz|Pure Quartz",
        "Ruby|Ruby",
        "Sapphire|Sapphire"
    };

    const auto all =
    {
        "Accessory_AT_1|Attack Pendant",
"Accessory_AT_2|Attack Pendant+1",
"Accessory_AT_3|Attack Pendant+2",
"Accessory_defense_1|Defense Pendant",
"Accessory_defense_2|Defense Pendant +1",
"Accessory_defense_3|Defense Pendant +2",
"Accessory_HeatResist_1|Heat Resistant Underwear",
"Accessory_HeatResist_2|Heat Resistant Underwear+1",
"Accessory_HeatResist_3|Heat Resistant Underwear+2",
"Accessory_HP_1|Life Pendant",
"Accessory_HP_2|Life Pendant+1",
"Accessory_HP_3|Life Pendant+2",
"Accessory_WorkSpeed_1|Pendant Of Diligence",
"Accessory_WorkSpeed_2|Pendant Of Diligence+1",
"Accessory_WorkSpeed_3|Pendant Of Diligence+2",
"Accessory_AquaResist_1|Ring Of Water Resistance",
"Accessory_AquaResist_2|Ring Of Water Resistance+1",
"Accessory_AquaResist_3|Ring Of Water Resistance+2",
"Accessory_DarkResist_1|Ring Of Dark Resistance",
"Accessory_DarkResist_2|Ring Of Dark Resistance+1",
"Accessory_DarkResist_3|Ring Of Dark Resistance+2",
"Accessory_DragonResist_1|Ring Of Dragon Resistance",
"Accessory_DragonResist_2|Ring Of Dragon Resistance+1",
"Accessory_DragonResist_3|Ring Of Dragon Resistance+2",
"Accessory_EarthResist_1|Ring Of Earth Resistance",
"Accessory_EarthResist_2|Ring Of Earth Resistance+1",
"Accessory_EarthResist_3|Ring Of Earth Resistance+2",
"Accessory_FireResist_1|Ring Of Flame Resistance",
"Accessory_FireResist_2|Ring Of Flame Resistance+1",
"Accessory_FireResist_3|Ring Of Flame Resistance+2",
"Accessory_IceResist_1|Ring Of Ice Resistance",
"Accessory_IceResist_2|Ring Of Ice Resistance+1",
"Accessory_IceResist_3|Ring Of Ice Resistance+2",
"Accessory_LeafResist_1|Ring Of Grass Resistance",
"Accessory_LeafResist_2|Ring Of Grass Resistance+1",
"Accessory_LeafResist_3|Ring Of Grass Resistance+2",
"Accessory_NormalResist_1|Ring Of Resistance",
"Accessory_NormalResist_2|Ring Of Resistance+1",
"Accessory_NormalResist_3|Ring Of Resistance+2",
"Accessory_ThunderResist_1|Ring Of Lightning Resistance",
"Accessory_ThunderResist_2|Ring Of Lightning Resistance+1",
"Accessory_ThunderResist_3|Ring Of Lightning Resistance+2",
"Accessory_CoolResist_1|Thermal Underwear",
"Accessory_CoolResist_2|Thermal Underwear+1",
"Accessory_CoolResist_3|Thermal Underwear+2",
"AssaultRifleBullet|Assault Rifle Ammo",
"Arrow|Arrow",
"RoughBullet|Coarse Ammo",
"InkBullet|Decal Ink",
"Arrow_Fire|Fire Arrow",
"HandgunBullet|Handgun Ammo",
"LaserBullet|Laser Ammo",
"MachingunBullet|Machine Gun Ammo",
"MagnumBullet|Magnum Ammo",
"Arrow_Poison|Poison Arrow",
"ExplosiveBullet|Rocket Ammo",
"RifleBullet|Rifle Ammo",
"ShotgunBullet|Shotgun Shells",
"AutoMealPouch_Tier2|Average Feed Bag",
"ClothArmor|Cloth Outfit(Common)",
"ClothArmor_2|Cloth Outfit(Uncommon)",
"ClothArmor_3|Cloth Outfit(Rare)",
"ClothArmor_4|Cloth Outfit(Epic)",
"ClothArmor_5|Cloth Outfit(Legendary)",
"CopperArmorCold|Cold Resistant Metal Armor(Common)",
"CopperArmorCold_2|Cold Resistant Metal Armor(Uncommon)",
"CopperArmorCold_3|Cold Resistant Metal Armor(Rare)",
"CopperArmorCold_4|Cold Resistant Metal Armor(Epic)",
"CopperArmorCold_5|Cold Resistant Metal Armor(Legendary)",
"FurArmorCold|Cold Resistant Pelt Armor(Common)",
"FurArmorCold_2|Cold Resistant Pelt Armor(Uncommon)",
"FurArmorCold_3|Cold Resistant Pelt Armor(Rare)",
"FurArmorCold_4|Cold Resistant Pelt Armor(Epic)",
"FurArmorCold_5|Cold Resistant Pelt Armor(Legendary)",
"IronArmorCold|Cold Resistant Refined Metal Armor(Common)",
"IronArmorCold_2|Cold Resistant Refined Metal Armor(Uncommon)",
"IronArmorCold_3|Cold Resistant Refined Metal Armor(Rare)",
"IronArmorCold_4|Cold Resistant Refined Metal Armor(Epic)",
"IronArmorCold_5|Cold Resistant Refined Metal Armor(Legendary)",
"StealArmorCold|Cold Resistant Pal Metal Armor(Common)",
"StealArmorCold_2|Cold Resistant Pal Metal Armor(Uncommon)",
"StealArmorCold_3|Cold Resistant Pal Metal Armor(Rare)",
"StealArmorCold_4|Cold Resistant Pal Metal Armor(Epic)",
"StealArmorCold_5|Cold Resistant Pal Metal Armor(Legendary)",
"FurHelmet|Feathered Hair Band(Common)",
"FurHelmet_2|Feathered Hair Band(Uncommon)",
"FurHelmet_3|Feathered Hair Band(Rare)",
"FurHelmet_4|Feathered Hair Band(Epic)",
"FurHelmet_5|Feathered Hair Band(Legendary)",
"AutoMealPouch_Tier5|Giant Feed Bag",
"CopperArmorHeat|Heat Resistant Metal Armor(Common)",
"CopperArmorHeat_2|Heat Resistant Metal Armor(Uncommon)",
"CopperArmorHeat_3|Heat Resistant Metal Armor(Rare)",
"CopperArmorHeat_4|Heat Resistant Metal Armor(Epic)",
"CopperArmorHeat_5|Heat Resistant Metal Armor(Legendary)",
"FurArmorHeat|Heat Resistant Pelt Armor(Common)",
"FurArmorHeat_2|Heat Resistant Pelt Armor(Uncommon)",
"FurArmorHeat_3|Heat Resistant Pelt Armor(Rare)",
"FurArmorHeat_4|Heat Resistant Pelt Armor(Epic)",
"FurArmorHeat_5|Heat Resistant Pelt Armor(Legendary)",
"AutoMealPouch_Tier4|Huge Feed Bag",
"IronArmorHeat|Heat Resistant Refined Metal Armor(Common)",
"IronArmorHeat_2|Heat Resistant Refined Metal Armor(Uncommon)",
"IronArmorHeat_3|Heat Resistant Refined Metal Armor(Rare)",
"IronArmorHeat_4|Heat Resistant Refined Metal Armor(Epic)",
"IronArmorHeat_5|Heat Resistant Refined Metal Armor(Legendary)",
"StealArmorHeat|Heat Resistant Pal Metal Armor(Common)",
"StealArmorHeat_2|Heat Resistant Pal Metal Armor(Uncommon)",
"StealArmorHeat_3|Heat Resistant Pal Metal Armor(Rare)",
"StealArmorHeat_4|Heat Resistant Pal Metal Armor(Epic)",
"StealArmorHeat_5|Heat Resistant Pal Metal Armor(Legendary)",
"AutoMealPouch_Tier3|Large Feed Bag",
"CopperArmor|Metal Armor(Common)",
"CopperArmor_2|Metal Armor(Uncommon)",
"CopperArmor_3|Metal Armor(Rare)",
"CopperArmor_4|Metal Armor(Epic)",
"CopperArmor_5|Metal Armor(Legendary)",
"CopperHelmet|Metal Helm(Common)",
"CopperHelmet_2|Metal Helm(Uncommon)",
"CopperHelmet_3|Metal Helm(Rare)",
"CopperHelmet_4|Metal Helm(Epic)",
"CopperHelmet_5|Metal Helm(Legendary)",
"FurArmor|Pelt Armor(Common)",
"FurArmor_2|Pelt Armor(Uncommon)",
"FurArmor_3|Pelt Armor(Rare)",
"FurArmor_4|Pelt Armor(Epic)",
"FurArmor_5|Pelt Armor(Legendary)",
"StealArmor|Pal Metal Armor(Common)",
"StealArmor_2|Pal Metal Armor(Uncommon)",
"StealArmor_3|Pal Metal Armor(Rare)",
"StealArmor_4|Pal Metal Armor(Epic)",
"StealArmor_5|Pal Metal Armor(Legendary)",
"StealHelmet|Pal Metal Helm(Common)",
"StealHelmet_2|Pal Metal Helm(Uncommon)",
"StealHelmet_3|Pal Metal Helm(Rare)",
"StealHelmet_4|Pal Metal Helm(Epic)",
"StealHelmet_5|Pal Metal Helm(Legendary)",
"IronArmor|Refined Metal Armor(Common)",
"IronArmor_2|Refined Metal Armor(Uncommon)",
"IronArmor_3|Refined Metal Armor(Rare)",
"IronArmor_4|Refined Metal Armor(Epic)",
"IronArmor_5|Refined Metal Armor(Legendary)",
"IronHelmet|Refined Metal Helm(Common)",
"IronHelmet_2|Refined Metal Helm(Uncommon)",
"IronHelmet_3|Refined Metal Helm(Rare)",
"IronHelmet_4|Refined Metal Helm(Epic)",
"IronHelmet_5|Refined Metal Helm(Legendary)",
"AutoMealPouch_Tier1|Small Feed Bag",
"ClothArmorCold|Tundra Outfit(Common)",
"ClothArmorCold_2|Tundra Outfit(Uncommon)",
"ClothArmorCold_3|Tundra Outfit(Rare)",
"ClothArmorCold_4|Tundra Outfit(Epic)",
"ClothArmorCold_5|Tundra Outfit(Legendary)",
"ClothArmorHeat|Tropical Outfit(Common)",
"ClothArmorHeat_2|Tropical Outfit(Uncommon)",
"ClothArmorHeat_3|Tropical Outfit(Rare)",
"ClothArmorHeat_4|Tropical Outfit(Epic)",
"ClothArmorHeat_5|Tropical Outfit(Legendary)",
"PalCrystal_Ex|Ancient Civilization Parts",
"Bone|Bone",
"Poppy|Beautiful Flowers",
"CrudeOil|Crude Oil",
"Claws|Claws",
"Cloth|Cloth",
"Coal|Coal",
"Cement|Cement",
"Charcoal|Charcoal",
"CarbonFiber|Carbon Fiber",
"MachineParts2|Circuit Board",
"ElectricOrgan|Electric Organ",
"Flour|Flour",
"Fiber|Fiber",
"FireOrgan|Flame Organ",
"GunPowder2|Gunpowder",
"PalItem_PlantSlime|Gumoss Leaf",
"Cloth2|High Quality Cloth",
"PalOil|High Quality Pal Oil",
"Horn|Horn",
"CopperIngot|Ingot",
"IceOrgan|Ice Organ",
"PalItem_CatMage|Katress Hair",
"Leather|Leather",
"MachineParts|Nails",
"CopperOre|Ore",
"PalFluid|Pal Fluids",
"Polymer|Polymer",
"Pal_crystal_L|Paldium Clump",
"Pal_crystal_S|Paldium Fragment",
"StealIngot|Pal Metal Ingot",
"Quartz|Pure Quartz",
"PalItem_CaptainPenguin|Punking Plume",
"IronIngot|Refined Ingot",
"Stone|Stone",
"Sulfur|Sulfur",
"PalItem_ColorfulBird|Tocotoco Feather",
"Venom|Venom Gland",
"Wood|Wood",
"Wool|Wool",
"PalEgg_Dark_01|Dark Egg",
"PalEgg_Dark_02|Dark Egg(2)",
"PalEgg_Dark_03|Large Dark Egg",
"PalEgg_Dark_04|Large Dark Egg(2)",
"PalEgg_Dark_05|Huge Dark Egg",
"PalEgg_Dragon_01|Dragon Egg",
"PalEgg_Dragon_02|Dragon Egg(2)",
"PalEgg_Dragon_03|Large Dragon Egg",
"PalEgg_Dragon_04|Large Dragon Egg(2)",
"PalEgg_Dragon_05|Huge Dragon Egg",
"PalEgg_Earth_01|Rocky Egg",
"PalEgg_Earth_02|Rough Egg(2)",
"PalEgg_Earth_03|Large Rocky Egg",
"PalEgg_Earth_04|Large Rocky Egg(2)",
"PalEgg_Earth_05|Huge Rocky Egg",
"PalEgg_Electricity_01|Electric Egg",
"PalEgg_Electricity_02|Electric Egg(2)",
"PalEgg_Electricity_03|Large Electric Egg",
"PalEgg_Electricity_04|Large Electric Egg(2)",
"PalEgg_Electricity_05|Huge Electric Egg",
"PalEgg_Fire_01|Scorching Egg",
"PalEgg_Fire_02|Scorching Egg(2)",
"PalEgg_Fire_03|Large Scorching Egg",
"PalEgg_Fire_04|Large Scorching Egg",
"PalEgg_Fire_05|Huge Scorching Egg",
"PalEgg_Ice_01|Frozen Egg",
"PalEgg_Ice_02|Frozen Egg(2)",
"PalEgg_Ice_03|Large Frozen Egg",
"PalEgg_Ice_04|Large Frozen Egg(2)",
"PalEgg_Ice_05|Huge Frozen Egg",
"PalEgg_Leaf_01|Verdant Egg",
"PalEgg_Leaf_02|Verdant Egg(2)",
"PalEgg_Leaf_03|Large Verdant Egg",
"PalEgg_Leaf_04|Large Verdant Egg(2)",
"PalEgg_Leaf_05|Huge Verdant Egg",
"PalEgg_Normal_01|Common Egg",
"PalEgg_Normal_02|Common Egg(2)",
"PalEgg_Normal_03|Large Common Egg",
"PalEgg_Normal_04|Large Common Egg(2)",
"PalEgg_Normal_05|Huge Common Egg",
"PalEgg_Water_01|Damp Egg",
"PalEgg_Water_02|Damp Egg(2)",
"PalEgg_Water_03|Large Damp Egg",
"PalEgg_Water_04|Large Damp Egg(2)",
"PalEgg_Water_05|Huge Damp Egg",
"SkillUnlock_Boar|Rushoar Saddle",
"SkillUnlock_CaptainPenguin|Captain Penguin Saddle",
"SkillUnlock_Carbunclo|Lifmunk Saddle",
"SkillUnlock_ColorfulBird|Tocotoco Saddle",
"SkillUnlock_DarkMutant|Dark Mutant Saddle",
"SkillUnlock_Deer|Eikthyrdeer Saddle",
"SkillUnlock_DreamDemon|Daedream Saddle",
"SkillUnlock_DrillGame|Digtoise Saddle",
"SkillUnlock_Eagle|Galeclaw Saddle",
"SkillUnlock_ElecLion|Boltmane Saddle",
"SkillUnlock_ElecPanda|Grizzbolt Saddle",
"SkillUnlock_FairyDragon|Elphidran Saddle",
"SkillUnlock_FeatherOstrich|Feather Ostrich Saddle",
"SkillUnlock_FengyunDeeper|Fenglope Saddle",
"SkillUnlock_FireKirin|Pyrin Saddle",
"SkillUnlock_FlameBuffalo|Arsox Saddle",
"SkillUnlock_FlowerDinosaur|Dinossom Saddle",
"SkillUnlock_FlowerRabbit|Flopie Saddle",
"SkillUnlock_FlyingManta|Celaray Saddle",
"SkillUnlock_Garm|Direhowl Saddle",
"SkillUnlock_GhostBeast|Maraith Saddle",
"SkillUnlock_GoldenHorse|Golden Horse Saddle",
"SkillUnlock_GrassMammoth|Mammorest Saddle",
"SkillUnlock_GrassPanda|Mossanda Saddle",
"SkillUnlock_GuardianDog|Guardian Dog Saddle",
"SkillUnlock_HadesBird|Helzypher Saddle",
"SkillUnlock_HawkBird|Nitewing Saddle",
"SkillUnlock_Hedgehog|Jolthog Saddle",
"SkillUnlock_HerculesBeetle|Hercules Beetle Saddle",
"SkillUnlock_Horus|Faleris Saddle",
"SkillUnlock_IceDeer|Reindrix Saddle",
"SkillUnlock_IceFox|Ice Fox Saddle",
"SkillUnlock_IceHorse|Frostallion Saddle",
"SkillUnlock_JetDragon|Jetragon Saddle",
"SkillUnlock_KingAlpaca|Kingpaca Saddle",
"SkillUnlock_KingBahamut|Blazamut Saddle",
"SkillUnlock_Kirin|Univolt Saddle",
"SkillUnlock_Kitsunebi|Foxpark Saddle",
"SkillUnlock_LazyDragon|Relaxaurus Saddle",
"SkillUnlock_LilyQueen|Lily Queen Saddle",
"SkillUnlock_Manticore|Blazehowl Saddle",
"SkillUnlock_Monkey|Tanzee Saddle",
"SkillUnlock_MopKing|Sweepa Saddle",
"SkillUnlock_NaughtyCat|Grintale saddle",
"SkillUnlock_NegativeOctopus|Killamari Saddle",
"SkillUnlock_Penguin|Pengullet Saddle",
"SkillUnlock_RaijinDaughter|Dazzi Saddle",
"SkillUnlock_RedArmorBird|Ragnahawk Saddle",
"SkillUnlock_SaintCentaur|Paladius Saddle",
"SkillUnlock_SakuraSaurus|Broncherry Saddle",
"SkillUnlock_Serpent|Surfent Saddle",
"SkillUnlock_SkyDragon|Quivern Saddle",
"SkillUnlock_Suzaku|Suzaku Saddle",
"SkillUnlock_ThunderBird|Breakon Saddle",
"SkillUnlock_ThunderDog|Rayhound Saddle",
"SkillUnlock_Umihebi|Jormuntide Saddle",
"SkillUnlock_VolcanicMonster|Reptyro Saddle",
"SkillUnlock_WeaselDragon|Chillet Saddle",
"SkillUnlock_WingGolem|Wing Golem Saddle",
"SkillUnlock_WindChimes|Hangyu Saddle",
"SkillUnlock_Yeti|Wumpo Saddle",
"SkillUnlock_Umihebi_Fire|Jormuntide Ignis Saddle",
"SkillUnlock_Deer_Ground|Eikthyrdeer Terra Saddle",
"SkillUnlock_Hedgehog_Ice|Jolthog Cryst Saddle",
"SkillUnlock_FlowerDinosaur_Electric|Dinossom Lux Saddle",
"SkillUnlock_GrassMammoth_Ice|Mammorest Cryst Saddle",
"SkillUnlock_LazyDragon_Electric|Relaxaurus Lux Saddle",
"SkillUnlock_FireKirin_Dark|Dark Pyrin Saddle",
"SkillUnlock_SakuraSaurus_Water|Water Broncherry Saddle",
"SkillUnlock_FairyDragon_Water|Water Elphidran Saddle",
"SkillUnlock_Manticore_Dark|Dark Kingferno Saddle",
"SkillUnlock_Suzaku_Water|Water Suzaku Saddle",
"SkillUnlock_Serpent_Ground|Aquadon Terra Saddle",
"SkillUnlock_VolcanicMonster_Ice|Ice Reptyro Saddle",
"SkillUnlock_IceHorse_Dark|Frostallion Noct Saddle",
"SkillUnlock_GrassPanda_Electric|Mossanda Lux Saddle",
"SkillUnlock_Yeti_Grass|Wumpo Botan",
"SkillUnlock_KingAlpaca_Ice|Kingpaca",
"SkillUnlock_BirdDragon_Ice|Vanwyrm Cryst",
"SkillUnlock_WindChimes_Ice|Hangyu Cryst Saddle",
"BLT|Burrito",
"BakedMeat_LazyCatfish|Broiled Dumund",
"BakedMeat_SakuraSaurus|Broncherry Rib Roast",
"BakedMushroom|Baked Mushrooms",
"Baked_Berries|Baked Berries",
"MeatSauce|Bolognese Sauce",
"Meat_SakuraSaurus|Broncherry Meat",
"Pan|Bread",
"Cake|Cake",
"CheeseBurger|Cheeseburger",
"ChickenSaute|Chikipi Saute",
"Carbonara|Carbonara",
"Meat_BerryGoat|Caprity Meat",
"Meat_ChickenPal|Chikipi Poultry",
"Sweet|Cotton Candy",
"CornSoup|Corn Soup",
"Chowder|Dumund Chowder",
"Egg|Egg",
"DeerLocoMoco|Eikthyrdeer Loco Moco",
"DeerStew|Eikthyrdeer Stew",
"Meat_Deer|Eikthyrdeer Venison",
"FriedChicken|Fried Chikipi",
"FriedEggs|Fried Eggs",
"FriedKelpie|Fried Kepsea",
"BakedMeat_ChickenPal|Grilled Chikipi",
"BakedMeat_Eagle|Grilled Galeclaw",
"BakedMeat_Kelpie|Grilled Kelpsea",
"Meat_Eagle|Galeclaw Poultry",
"GrilledMeat|Grilled Meat",
"GenghisKhan|Grilled Lamball",
"BakedMeat_BerryGoat|Herb Roasted Caprity",
"Honey|Honey",
"HotDog|Hot Dog",
"HotMilk|Hot Milk",
"GrilledSheepHerbs|Herb Roasted Lamball",
"Hamburger|Hamburger",
"JamBun|Jam-filled Bun",
"BakedMeat_SheepBall|Lamball Kebab",
"Meat_SheepBall|Lamball Mutton",
"Lettuce|Lettuce",
"BakedMeat_CowPal|Moazzarina Steak",
"BakedMeat_GrassMammoth|Mammorest Steak",
"CheeseBurger_2|Mozzarina Cheeseburger",
"Meat_CowPal|Mozzarina Meat",
"Meat_GrassMammoth|Mammorest Meat",
"Hamburger_2|Mozzarina Hamburger",
"Milk|Milk",
"MarinatedMushrooms|Marinated Mushrooms",
"MushroomSoup|Mushroom Soup",
"Mushroom|Mushroom",
"Omelet|Omelet",
"Pancake|Pancake",
"Pizza|Pizza",
"BaconEggs|Rushoar Bacon 'n' Eggs",
"BakedMeat_Boar|Roast Rushoar",
"BakedMeat_Deer|Roast Eikthyrdeer",
"BakedMeat_IceDeer|Roast Reindrix",
"Meat_Boar|Roshoar Pork",
"Meat_IceDeer|Reindrix Venison",
"Meat_Kelpie|Raw Kelpsea",
"Meat_LazyCatfish|Raw Dumund",
"Meat|Raw Meat",
"HotDog_2|Rushoar Hot Dog",
"StewedIceDeer|Reindrix Stew",
"Berries|Red Wild Berries",
"Eaglestew|Stewed Galeclaw",
"FriedVegetables|Stir-fried Veggies",
"Salad|Salad",
"MushroomStew|Stewed Mushrooms",
"Tomato|Tomato",
"Wheat|Wheat",
"Head012|Bowler Hat(Common)",
"Head012_2|Bowler Hat(Uncommon)",
"Head012_3|Bowler Hat(Rare)",
"Head012_4|Bowler Hat(Epic)",
"Head012_5|Bowler Hat(Legendary)",
"Head009|Explorer Cap(Common)",
"Head009_2|Explorer Cap(Uncommon)",
"Head009_3|Explorer Cap(Rare)",
"Head009_4|Explorer Cap(Epic)",
"Head009_5|Explorer Cap(Legendary)",
"Head011|Farming Hat(Common)",
"Head011_2|Farming Hat(Uncommon)",
"Head011_3|Farming Hat(Rare)",
"Head011_4|Farming Hat(Epic)",
"Head011_5|Farming Hat(Legendary)",
"Head002|Golden Crown(Common)",
"Head002_2|Golden Crown(Uncommon)",
"Head002_3|Golden Crown(Rare)",
"Head002_4|Golden Crown(Epic)",
"Head002_5|Golden Crown(Legendary)",
"Head010|Graduation Cap(Common)",
"Head010_2|Graduation Cap(Uncommon)",
"Head010_3|Graduation Cap(Rare)",
"Head010_4|Graduation Cap(Epic)",
"Head010_5|Graduation Cap(Legendary)",
"Head014|Grinning Tocotoco Cap(Common)",
"Head014_2|Grinning Tocotoco Cap(Uncommon)",
"Head014_3|Grinning Tocotoco Cap(Rare)",
"Head014_4|Grinning Tocotoco Cap(Epic)",
"Head014_5|Grinning Tocotoco Cap(Legendary)",
"Head015|Gusmoss Cap(Common)",
"Head015_2|Gusmoss Cap(Uncommon)",
"Head015_3|Gusmoss Cap(Rare)",
"Head015_4|Gusmoss Cap(Epic)",
"Head015_5|Gusmoss Cap(Legendary)",
"Head006|Helmet(Common)",
"Head006_2|Helmet(Uncommon)",
"Head006_3|Helmet(Rare)",
"Head006_4|Helmet(Epic)",
"Head006_5|Helmet(Legendary)",
"Head017|Katress Cap(Common)",
"Head017_2|Katress Cap(Uncommon)",
"Head017_3|Katress Cap(Rare)",
"Head017_4|Katress Cap(Epic)",
"Head017_5|Katress Cap(Legendary)",
"Head003|Long-eared Headband(Common)",
"Head003_2|Long-eared Headband(Uncommon)",
"Head003_3|Long-eared Headband(Rare)",
"Head003_4|Long-eared Headband(Epic)",
"Head003_5|Long-eared Headband(Legendary)",
"Head001|Monarch's Crown(Common)",
"Head001_2|Monarch's Crown(Uncommon)",
"Head001_3|Monarch's Crown(Rare)",
"Head001_4|Monarch's Crown(Epic)",
"Head001_5|Monarch's Crown(Legendary)",
"Head016|Penking Cap(Common)",
"Head016_2|Penking Cap(Uncommon)",
"Head016_3|Penking Cap(Rare)",
"Head016_4|Penking Cap(Epic)",
"Head016_5|Penking Cap(Legendary)",
"Head005|Soft Hat(Common)",
"Head005_2|Soft Hat(Uncommon)",
"Head005_3|Soft Hat(Rare)",
"Head005_4|Soft Hat(Epic)",
"Head005_5|Soft Hat(Legendary)",
"Head007|Silk Hat(Common)",
"Head007_2|Silk Hat(Uncommon)",
"Head007_3|Silk Hat(Rare)",
"Head007_4|Silk Hat(Epic)",
"Head007_5|Silk Hat(Legendary)",
"Head008|Tricorne(Common)",
"Head008_2|Tricorne(Uncommon)",
"Head008_3|Tricorne(Rare)",
"Head008_4|Tricorne(Epic)",
"Head008_5|Tricorne(Legendary)",
"Head013|Tocotoco Cap(Common)",
"Head013_2|Tocotoco Cap(Uncommon)",
"Head013_3|Tocotoco Cap(Rare)",
"Head013_4|Tocotoco Cap(Epic)",
"Head013_5|Tocotoco Cap(Legendary)",
"Head004|Witch Hat(Common)",
"Head004_2|Witch Hat(Uncommon)",
"Head004_3|Witch Hat(Rare)",
"Head004_4|Witch Hat(Epic)",
"Head004_5|Witch Hat(Legendary)",
"LuxuryMedicines|High Grade Medical Supplies",
"Herbs|Low Quality Medical Supplies",
"Medicines|Medical Supplies",
"MindControlDrug|Mind Control Meds",
"StatusPointResetSan|Memory Wiping Medicine",
"Narcotic|Strange Juice",
"Opium|Suspicious Juice",
"Unko_S|Dung",
"TechnologyBook_G3|Future Technical Manual",
"TechnologyBook_G1|High Grade Technical Manual",
"Unko_L|Huge Dung Pile",
"TechnologyBook_G2|Innovative Technical Manual",
"PalUpgradeStone3|Large Pal Soul",
"Relic|Lifmunk Effigy",
"PalUpgradeStone2|Medium Pal Soul",
"PalItem_ToSell_01|Precious Dragon Stone",
"PalItem_ToSell_02|Precious Plume",
"PalItem_ToSell_03|Precious Entrails",
"PalItem_ToSell_04|Precious Claw",
"PalItem_ToSell_05|Precious Pelt",
"PalUpgradeStone|Small Pal Soul",
"PalSphere_Giga|Giga Sphere",
"PalSphere_Tera|Hyper Sphere",
"PalSphere_Legend|Legendary Sphere",
"PalSphere_Mega|Mega Sphere",
"PalSphere|Pal Sphere",
"PalSphere_Robbery|Radar Sphere",
"PalSphere_Master|Ultra Sphere",
"PalSphere_Debug|Debug Sphere",
"BerrySeeds|Berry Seeds",
"LettuceSeeds|Lettuce Seeds",
"TomatoSeeds|Tomato Seeds",
"WheatSeeds|Wheat Seeds",
"Shield_01|Common Shield",
"TreasureBoxKey01|Copper Key",
"Glider_Super|Giga Glider",
"Shield_03|Giga Shield",
"TreasureBoxKey03|Golden Key",
"Glider_Legendary|HyperGlider",
"Lantern|Hip Lantern",
"Shield_04|HyperShield",
"Torch|Hand-held Torch",
"Axe_Tier_01|Metal Ax",
"Pickaxe_Tier_01|Metal Pickaxe",
"Glider_Good|Mega Glider",
"Shield_02|Mega Shield",
"MeatCutterKnife|Meat Cleaver",
"Glider_Old|Normal Parachute",
"Axe_Tier_02|Refined Metal Ax",
"Pickaxe_Tier_02|Refined Metal Pickaxe",
"RepairKit|Repair Kit",
"Axe_Tier_00|Stone Ax",
"Pickaxe_Tier_00|Stone Pickaxe",
"TreasureBoxKey02|Silver Key",
"AssaultRifle_Default1|Assault Rifle(Common)",
"AssaultRifle_Default2|Assault Rifle(Uncommon)",
"AssaultRifle_Default3|Assault Rifle(Rare)",
"AssaultRifle_Default4|Assault Rifle(Epic)",
"AssaultRifle_Default5|Assault Rifle(Legendary)",
"Bat2|Bat",
"Spear_SoldierBee|Beegarde's Spear",
"BowGun|Crossbow(Common)",
"BowGun_2|Crossbow(Uncommon)",
"BowGun_3|Crossbow(Rare)",
"BowGun_4|Crossbow(Epic)",
"BowGun_5|Crossbow(Legendary)",
"DecalGun_1|Decal Gun 1",
"DecalGun_2|Decal Gun 2",
"DecalGun_3|Decal Gun 3",
"DecalGun_4|Decal Gun 4",
"DecalGun_5|Decal Gun 5",
"DoubleBarrelShotgun|Double-barreled Shotgun",
"Spear_QueenBee|Elizabee's Staff",
"BowGun_Fire|Fire Arrow Crossbow",
"Bow_Fifth|Five Shot Bow",
"Bow_Fire|Fire Bow",
"FragGrenade|Frag Grenade",
"GrapplingGun|Grappling Gun",
"GrapplingGun2|Mega Grappling Gun",
"GrapplingGun3|Giga Grappling Gun",
"GrapplingGun4|Hyper Grappling Gun",
"HomingSphereLauncher|Homing Sphere Launcher",
"FragGrenade_Fire|Incendiary Grenade",
"FragGrenade_Ice|Ice Grenade",
"MakeshiftHandgun|Inferior Handgun",
"LaserRifle|Laser Rifle",
"Spear_ForestBoss|Lily's Spear",
"Musket|Musket",
"Spear_2|Metal Spear",
"WeakerBow|Old Bow(Common)",
"WeakerBow_2|Old Bow(Uncommon)",
"WeakerBow_3|Old Bow(Rare)",
"WeakerBow_4|Old Bow(Epic)",
"WeakerBow_5|Old Bow(Legendary)",
"BowGun_Poison|Poison Arrow Crossbow",
"Bow_Poison|Poison Bow",
"HandGun_Default|Pistol(Common)",
"HandGun_Default_2|Pistol(Uncommon)",
"HandGun_Default_3|Pistol(Rare)",
"HandGun_Default_4|Pistol(Epic)",
"HandGun_Default_5|Pistol(Legendary)",
"PumpActionShotgun|Pump Action Shotgun(Common)",
"PumpActionShotgun_2|Pump Action Shotgun(Uncommon)",
"PumpActionShotgun_3|Pump Action Shotgun(Rare)",
"PumpActionShotgun_4|Pump Action Shotgun(Epic)",
"PumpActionShotgun_5|Pump Action Shotgun(Legendary)",
"Launcher_Default|Rocket Launcher(Common)",
"Launcher_Default_2|Rocket Launcher(Uncommon)",
"Launcher_Default_3|Rocket Launcher(Rare)",
"Launcher_Default_4|Rocket Launcher(Epic)",
"Launcher_Default_5|Rocket Launcher(Legendary)",
"RecurveBow|RecurveBow",
"Spear_3|Refined Metal Spear",
"FragGrenade_Elec|Shock Grenade",
"ElecBaton|Stun Baton",
"SingleShotRifle|Single-shot Rifle",
"SniperRifle_Default|Sniper Rifle",
"Spear|Stone Spear",
"SphereLauncher|Scatter Sphere Launcher",
"SphereLauncher_Once|Single-shot Sphere Launcher",
"Sword|Sword",
"Bow_triple|Triple Shot Bow",
"Bat|Wooden Club",
"Diamond|Diamond",
"Eemerald|Emerald",
"Money|Gold Coin",
"Quartz|Pure Quartz",
"Ruby|Ruby",
"Sapphire|Sapphire",
    };
}