#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x28 (0x158 - 0x130)
// BlueprintGeneratedClass BP_AIAction_CanCombatBase.BP_AIAction_CanCombatBase_C
class UBP_AIAction_CanCombatBase_C : public UPalAIActionBase
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x130(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UPalDamageReactionComponent*           DamageReaction;                                    // 0x138(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	enum class EPalAIResponseType                CurrentBehavior;                                   // 0x140(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         NextCombatModeChange;                              // 0x141(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	uint8                                        Pad_2FEE[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UClass*                                TempEncountClass;                                  // 0x148(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	class UPalAISensorComponent*                 TSCache_AISensorComponent;                         // 0x150(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_AIAction_CanCombatBase_C* GetDefaultObj();

	void SelfMoveToLocation(const struct FVector& Goal, class APalAIController* CallFunc_GetPalAIController_ReturnValue, enum class EPathFollowingRequestResult CallFunc_MoveToLocation_ReturnValue);
	void IsLeader(bool* Leader, class AController* CallFunc_GetController_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsLeader_ReturnValue);
	void OnSquadMemberDeadEvent(const struct FPalDeadInfo& DeadInbfo, const TArray<class APalCharacter*>& KillerList, class AActor* TempKiller, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, class APawn* CallFunc_K2_GetPawn_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue, class UPalBattleManager* CallFunc_GetBattleManager_ReturnValue, class AController* CallFunc_GetController_ReturnValue_2, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue, class APalAIController* CallFunc_GetPalAIController_ReturnValue, class APalCharacter* CallFunc_SelectResponseBySenses_OutTargetCharacter, enum class EPalAIResponseType CallFunc_SelectResponseBySenses_ReturnValue, class UPalAIBlackboardBase* CallFunc_GetMyPalBlackboard_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, class UBP_PalAIBlackboard_Common_C* K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common, bool K2Node_DynamicCast_bSuccess_1, class AController* CallFunc_GetController_ReturnValue_3, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue_1, bool CallFunc_IsInSightKillerAndDeadBody_ReturnValue);
	void StartFriendlyLookatMode(class AActor* TargetActor, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue);
	void GetLeaderPalBrackBoard(class UBP_PalAIBlackboard_Common_C** BB, class APalAIController* CallFunc_GetPalAIController_ReturnValue, class UPalAIBlackboardBase* CallFunc_GetLeaderPalBlackboard_ReturnValue, class UBP_PalAIBlackboard_Common_C* K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common, bool K2Node_DynamicCast_bSuccess);
	void Fun_Damage_AIResponse(const struct FPalDamageResult& DamageResult, class APalCharacter* TempTargetActor, const TArray<class APalCharacter*>& AttackerList, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class AController* CallFunc_GetController_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class APawn* CallFunc_K2_GetPawn_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UPalBattleManager* CallFunc_GetBattleManager_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, class AController* CallFunc_GetController_ReturnValue_1, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue_1, class APalCharacter* CallFunc_SelectResponseBySenses_OutTargetCharacter, enum class EPalAIResponseType CallFunc_SelectResponseBySenses_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess);
	void SearchDeadEdibleBody(bool* ChangeNextAction, class AActor* TempTarget, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_1, TArray<class APalCharacter*>& CallFunc_SightCheckAllEdibleDeadNPC_InSightCharacters, class APalCharacter* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue);
	void SightCheckAndResponse(enum class EPalAIResponseType Current, bool OverrideIsDamage, bool* ChangeNextAction, const TArray<class APalCharacter*>& TempTargetList, class AActor* TempTarget, class AActor* CallFunc_SightCheck_Target, enum class EPalAIResponseType CallFunc_SightCheck_ResponseType, bool CallFunc_SightResponse_ChangeNextAction);
	void SightResponse(class AActor* Target, enum class EPalAIResponseType ResponseType, bool* ChangeNextAction, bool K2Node_SwitchEnum_CmpSuccess);
	void SightCheck(enum class EPalAIResponseType CurrentState, bool OverrideIsDamage, class AActor** Target, enum class EPalAIResponseType* ResponseType, const TArray<class APalCharacter*>& TempTargetList, TArray<class APalCharacter*>& CallFunc_SightCheckAllPlayer_InSightPlayers, TArray<class APalCharacter*>& CallFunc_SightCheckAllAliveNPC_InSightCharacters, class APalCharacter* CallFunc_SelectResponseBySenses_OutTargetCharacter, enum class EPalAIResponseType CallFunc_SelectResponseBySenses_ReturnValue, class UPalCheatManager* CallFunc_GetPalCheatManager_ReturnValue, bool CallFunc_IsDisableEnemyEyeSight_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetLeader(class APalCharacter** Leader, class APalAIController* CallFunc_GetPalAIController_ReturnValue, class APalCharacter* CallFunc_GetSquadLeader_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void GetSelfPalBlackBoard(class UBP_PalAIBlackboard_Common_C** PalBlackBoard, class APalAIController* CallFunc_GetPalAIController_ReturnValue, class UPalAIBlackboardBase* CallFunc_GetMyPalBlackboard_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UBP_PalAIBlackboard_Common_C* K2Node_DynamicCast_AsBP_Pal_AIBlackboard_Common, bool K2Node_DynamicCast_bSuccess);
	void SoundEvent(const struct FVector& EmitLocation);
	void DamageEventToCombatMode(const struct FPalDamageResult& DamageResult, class UPalBattleManager* CallFunc_GetBattleManager_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, bool CallFunc_TargetIsPlayerOrPlayersOtomoPal_ReturnValue, bool CallFunc_Greater_IntInt_ReturnValue, class UPalBattleManager* CallFunc_GetBattleManager_ReturnValue_1);
	void StartEscapeMode(class AActor* TargetActor, class AController* CallFunc_GetController_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue);
	void StartWarningMode(const struct FVector& AttentionLocation, class AController* CallFunc_GetController_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue);
	void StartCombatMode(class AActor* TargetActor, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetAIActionClassParameter_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, class AController* CallFunc_GetController_ReturnValue, class UPalBattleManager* CallFunc_GetBattleManager_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_TargetIsPlayerOrPlayersOtomoPal_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class AController* CallFunc_GetController_ReturnValue_2, class APalAIController* K2Node_DynamicCast_AsPal_AIController_1, bool K2Node_DynamicCast_bSuccess_2, class AController* CallFunc_GetController_ReturnValue_3, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UPalStaticCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue);
	void ActionResume(class APawn* ControlledPawn);
	void ActionStart(class APawn* ControlledPawn);
	void ActionPause(class APawn* ControlledPawn);
	void ActionFinished(class APawn* ControlledPawn, enum class EPawnActionResult WithResult);
	void ActionAbort(class APawn* ControlledPawn);
	void ExecuteUbergraph_BP_AIAction_CanCombatBase(int32 EntryPoint, class APawn* K2Node_Event_ControlledPawn, class APawn* K2Node_Event_ControlledPawn_3, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APawn* K2Node_Event_ControlledPawn_2, class APawn* K2Node_Event_ControlledPawn_1, enum class EPawnActionResult K2Node_Event_WithResult, class AController* CallFunc_GetController_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class APawn* K2Node_Event_ControlledPawn_4, class AController* CallFunc_GetController_ReturnValue_2, class APawn* CallFunc_K2_GetPawn_ReturnValue, class AController* CallFunc_GetController_ReturnValue_3, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_2, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, bool CallFunc_GetIsSquadBehaviour_ReturnValue, class UPalSquad* CallFunc_GetSquad_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class AController* CallFunc_GetController_ReturnValue_4, class APalAIController* K2Node_DynamicCast_AsPal_AIController_1, bool K2Node_DynamicCast_bSuccess_1, class AController* CallFunc_GetController_ReturnValue_5, bool CallFunc_GetIsSquadBehaviour_ReturnValue_1, class APawn* CallFunc_K2_GetPawn_ReturnValue_1, class UPalSquad* CallFunc_GetSquad_ReturnValue_1, class UPalDamageReactionComponent* CallFunc_GetComponentByClass_ReturnValue_3, bool CallFunc_IsValid_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class AController* CallFunc_GetController_ReturnValue_6, class UPalAISensorComponent* CallFunc_GetComponentByClass_ReturnValue_4);
};

}


