#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x90 (0x130 - 0xA0)
// BlueprintGeneratedClass BP_AIADamageReaction.BP_AIADamageReaction_C
class UBP_AIADamageReaction_C : public UPalAIDamageReactionComponent
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xA0(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	TSoftObjectPtr<class UPalAIActionComponent>  PalAIActionComponent;                              // 0xA8(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, InstancedReference, HasGetValueTypeHash)
	TSoftObjectPtr<class UPalDamageReactionComponent> DamageReactionComponent;                           // 0xD8(0x30)(Edit, BlueprintVisible, DisableEditOnInstance, InstancedReference, HasGetValueTypeHash)
	class UPalDamageReactionComponent*           LocalDamageReactionComponent;                      // 0x108(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                        OnDamageIgnoreAIActionArray;                       // 0x110(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	double                                       StepPercentage;                                    // 0x120(0x8)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APalCharacter*                         DefaultPawn;                                       // 0x128(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_AIADamageReaction_C* GetDefaultObj();

	void IsNooseTrapAction(bool* IsNoose, class AActor* CallFunc_GetSelfPawn_Actor, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalActionBase* CallFunc_GetCurrentAction_ReturnValue, class UBP_ActionNooseTrap_C* K2Node_DynamicCast_AsBP_Action_Noose_Trap, bool K2Node_DynamicCast_bSuccess);
	void OnHitNooseTrap(class AActor* TrapActor, const struct FVector& FixPos, class AActor* CallFunc_GetOwner_ReturnValue, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* CallFunc_GetComponentByClass_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class AActor* CallFunc_GetSelfPawn_Actor, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void OnChangeTrapMovingPanel(bool Exist, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_1, bool K2Node_DynamicCast_bSuccess_1, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetCharacterParam(class UPalCharacterParameterComponent** CPC, class AActor* CallFunc_GetOwner_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue);
	void OnChangeTrapLegHold(bool Exist, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_1, bool K2Node_DynamicCast_bSuccess_1, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void IsPlayElecShockAction(bool* IsSlecShock, class AActor* CallFunc_GetSelfPawn_Actor, bool CallFunc_IsValid_ReturnValue, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalActionBase* CallFunc_GetCurrentAction_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UBP_ActionReaction_ElectricShock_C* K2Node_DynamicCast_AsBP_Action_Reaction_Electric_Shock, bool K2Node_DynamicCast_bSuccess);
	void GetSelfPawn(class AActor** Actor);
	void CheckIgnoreAction(bool* IsIgnore, int32 Temp_int_Array_Index_Variable, class AActor* CallFunc_GetSelfPawn_Actor, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalActionBase* CallFunc_GetCurrentAction_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, class UClass* K2Node_ClassDynamicCast_AsPal_Action_Waza_Base, bool K2Node_ClassDynamicCast_bSuccess, class UClass* CallFunc_Array_Get_Item, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable, class UPawnAction* CallFunc_GetCurrentAction_BP_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void HasSideStep(bool* HasSideStep, enum class EPalActionType Temp_byte_Variable, enum class EPalGeneralMontageType Temp_byte_Variable_1, enum class EPalGeneralMontageType Temp_byte_Variable_2, class AActor* CallFunc_GetSelfPawn_Actor, class UPalStaticCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class AActor* CallFunc_GetSelfPawn_Actor_1, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_2, class UAnimMontage* CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, class UAnimMontage* CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_4, TSubclassOf<class UPalActionBase> CallFunc_Map_Find_Value_2, bool CallFunc_Map_Find_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue_3, enum class EPalActionType Temp_byte_Variable_3, TSubclassOf<class UPalActionBase> CallFunc_Map_Find_Value_3, bool CallFunc_Map_Find_ReturnValue_3, bool CallFunc_IsValidClass_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_4, bool CallFunc_BooleanAND_ReturnValue_5);
	void IsRiding(bool* IsRiding, class AActor* CallFunc_GetSelfPawn_Actor, bool CallFunc_IsValid_ReturnValue, class UPalRiderComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_IsRiding_ReturnValue);
	void OnEachDamage(const struct FPalEachDamageRactionInfo& EachReactionInfo, bool CallFunc_IsNooseTrapAction_IsNoose, class AActor* CallFunc_GetSelfPawn_Actor, bool CallFunc_IsValid_ReturnValue, class UPalStaticCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, double CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_CheckIgnoreAction_IsIgnore, class AActor* CallFunc_GetOwner_ReturnValue, class APlayerController* K2Node_DynamicCast_AsPlayer_Controller, bool K2Node_DynamicCast_bSuccess, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess_1, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_1, bool K2Node_DynamicCast_bSuccess_2, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_HasSideStep_HasSideStep);
	void OnDamageReaction(const struct FPalDamageRactionInfo& ReactionInfo, class AActor* CallFunc_GetSelfPawn_Actor, class AActor* CallFunc_GetSelfPawn_Actor_1, bool CallFunc_IsValid_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsPlayElecShockAction_IsSlecShock, bool CallFunc_IsNooseTrapAction_IsNoose, bool CallFunc_BooleanOR_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_1, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_GetOwner_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_2, class APlayerController* K2Node_DynamicCast_AsPlayer_Controller, bool K2Node_DynamicCast_bSuccess_2, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_2, bool K2Node_DynamicCast_bSuccess_3, bool CallFunc_IsValidSoftObjectReference_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_IsRiding_IsRiding, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter_1, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter_2, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue_1, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue_2);
	void OnSleep(int32 LastDamage, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void OnDead(const struct FPalDeadInfo& DeadInfo, const struct FPalAIActionDynamicParameter& AIActionParam, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, bool CallFunc_IsNooseTrapAction_IsNoose, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_1, bool K2Node_DynamicCast_bSuccess_1, class UPalAIActionBase* CallFunc_SetActionClassParameter_ReturnValue_1, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_2, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_2, bool K2Node_DynamicCast_bSuccess_2, bool CallFunc_EqualEqual_ByteByte_ReturnValue, const struct FPalAIActionDynamicParameter& K2Node_MakeStruct_PalAIActionDynamicParameter, class AActor* CallFunc_GetOwner_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess_3, class APawn* CallFunc_K2_GetPawn_ReturnValue, class APalPlayerCharacter* K2Node_DynamicCast_AsPal_Player_Character, bool K2Node_DynamicCast_bSuccess_4, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue_3, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component_3, bool K2Node_DynamicCast_bSuccess_5, bool CallFunc_IsValid_ReturnValue_1);
	void Setup_AIDamageReaction();
	void Reset_AIDamageReaction();
	void ExecuteUbergraph_BP_AIADamageReaction(int32 EntryPoint, class UPalDamageReactionComponent* CallFunc_GetComponentByClass_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class AActor* CallFunc_GetOwner_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* CallFunc_GetComponentByClass_ReturnValue_1, class APawn* CallFunc_K2_GetPawn_ReturnValue, TSoftObjectPtr<class UPalAIActionComponent> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess_1, bool Temp_bool_Has_Been_Initd_Variable, class UObject* CallFunc_Conv_SoftObjectReferenceToObject_ReturnValue, class UPalDamageReactionComponent* K2Node_DynamicCast_AsPal_Damage_Reaction_Component, bool K2Node_DynamicCast_bSuccess_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, class UPalCharacterParameterComponent* CallFunc_GetCharacterParam_CPC, class UPalCharacterParameterComponent* CallFunc_GetCharacterParam_CPC_1, class UPalCharacterParameterComponent* CallFunc_GetCharacterParam_CPC_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_5, class UPalCharacterParameterComponent* CallFunc_GetCharacterParam_CPC_3, bool Temp_bool_IsClosed_Variable, TSoftObjectPtr<class UPalDamageReactionComponent> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_6, bool CallFunc_IsValid_ReturnValue);
};

}


