#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x68 (0x90 - 0x28)
// BlueprintGeneratedClass BP_HitEffectSlot.BP_HitEffectSlot_C
class UBP_HitEffectSlot_C : public UPalHitEffectSlot
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x28(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<TSoftObjectPtr<class UNiagaraSystem>> PreLoadList;                                       // 0x30(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UNiagaraSystem*>                LoadCache;                                         // 0x40(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         IsCrying;                                          // 0x50(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_24B7[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	TArray<class UClass*>                        RockBPList;                                        // 0x58(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UClass*>                        TreeBPList;                                        // 0x68(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                         NewVar_0;                                          // 0x78(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_24BA[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FString                                RockBPName;                                        // 0x80(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_HitEffectSlot_C* GetDefaultObj();

	void PlayHitSound(struct FPalDamageInfo& PalDamageInfo, enum class EPalBodyPartsType Temp_byte_Variable, class UAkAudioEvent* Temp_object_Variable, class UAkAudioEvent* Temp_object_Variable_1, class UAkAudioEvent* Temp_object_Variable_2, class UAkAudioEvent* Temp_object_Variable_3, class UPalHUDService* CallFunc_GetHUDService_ReturnValue, class APawn* CallFunc_GetPlayerPawn_ReturnValue, class UAkAudioEvent* K2Node_Select_Default, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
	void IsEnableCameraShake(bool* IsEnable, class UPalOptionSubsystem* CallFunc_GetOptionSubsystem_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FPalOptionGraphicsSettings& CallFunc_GetGraphicsSettings_ReturnValue);
	void PlayCameraShakeAndSoundEffect(enum class EPalWazaCategory Category, class AActor* Attacker, bool SpecializedEffectPlayed, bool CallFunc_IsEnableCameraShake_IsEnable, class APalPlayerCharacter* K2Node_DynamicCast_AsPal_Player_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_EqualEqual_ByteByte_ReturnValue, class APalPlayerController* CallFunc_GetPalPlayerController_ReturnValue, FDelegateProperty_ Temp_delegate_Variable, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, int32 CallFunc_PostEvent_ReturnValue, class APlayerCameraManager* CallFunc_GetPlayerCameraManager_ReturnValue_1, class UPalShooterComponent* CallFunc_GetComponentByClass_ReturnValue, class UCameraShakeBase* CallFunc_StartCameraShake_ReturnValue, class APalWeaponBase* CallFunc_GetHasWeapon_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, bool CallFunc_BooleanAND_ReturnValue_1);
	void SpawnSpecializationEffect(class AActor* Attacker, const struct FVector& Location, double EffectScale, bool* Played, class UPalShooterComponent* LocalShooter, FDelegateProperty_ Temp_delegate_Variable, class UPalShooterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, FDelegateProperty_ Temp_delegate_Variable_1, int32 CallFunc_PostEvent_ReturnValue, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable_1, FDelegateProperty_ Temp_delegate_Variable_2, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable_2, class UPalCharacterCameraComponent* CallFunc_GetComponentByClass_ReturnValue_1, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, const struct FRotator& CallFunc_FindLookAtRotation_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, FDelegateProperty_ Temp_delegate_Variable_3, int32 CallFunc_PostEvent_ReturnValue_1, int32 CallFunc_PostEvent_ReturnValue_2, class UPalCharacterCameraComponent* CallFunc_GetComponentByClass_ReturnValue_2, class UObject* CallFunc_GetOuterObject_ReturnValue, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue_1, class UPalFoliageDamageReactionComponent* K2Node_DynamicCast_AsPal_Foliage_Damage_Reaction_Component, bool K2Node_DynamicCast_bSuccess, const struct FRotator& CallFunc_FindLookAtRotation_ReturnValue_1, TArray<struct FAkExternalSourceInfo>& Temp_struct_Variable_3, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_PostEvent_ReturnValue_3, bool CallFunc_Less_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class UClass* CallFunc_Array_Get_Item, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue_1, const struct FTransform& CallFunc_MakeTransform_ReturnValue_1, class APalWeaponBase* CallFunc_GetHasWeapon_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, class ABP_AxeBase_C* K2Node_DynamicCast_AsBP_Axe_Base, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_FindOwnerActor_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, bool CallFunc_EqualEqual_ClassClass_ReturnValue, bool CallFunc_ClassIsChildOf_ReturnValue, bool CallFunc_BooleanOR_ReturnValue, class APalWeaponBase* CallFunc_GetHasWeapon_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue_1, class ABP_PickaxeBase_C* K2Node_DynamicCast_AsBP_Pickaxe_Base, bool K2Node_DynamicCast_bSuccess_2, class AActor* CallFunc_FindOwnerActor_ReturnValue_1, class UClass* CallFunc_GetObjectClass_ReturnValue_1, const class FString& CallFunc_GetClassDisplayName_ReturnValue, bool CallFunc_StartsWith_ReturnValue, float CallFunc_Conv_FloatToVector_InFloat_ImplicitCast, float CallFunc_Conv_FloatToVector_InFloat_ImplicitCast_1);
	void SpawnSneakAttackEffect(const struct FVector& Location, const struct FTransform& CallFunc_MakeTransform_ReturnValue);
	void SpawnElementalHitEffectBullet(enum class EPalElementType Element, const struct FVector& Location, double EffectScale, TSoftObjectPtr<class UNiagaraSystem> EffectPath, double Scale, bool K2Node_SwitchEnum_CmpSuccess, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, bool CallFunc_IsValidSoftObjectReference_ReturnValue, float CallFunc_Conv_FloatToVector_InFloat_ImplicitCast);
	void SpawnElementalHitEffectNear(enum class EPalElementType Element, const struct FVector& Location, double EffectScale, TSoftObjectPtr<class UNiagaraSystem> EffectPath, double Scale, bool K2Node_SwitchEnum_CmpSuccess, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, float CallFunc_Conv_FloatToVector_InFloat_ImplicitCast);
	void SpawnElementalHitEffectFar(enum class EPalElementType Element, const struct FVector& Location, double EffectScale, bool IsPoison, TSoftObjectPtr<class UNiagaraSystem> EffectPath, double Scale, bool K2Node_SwitchEnum_CmpSuccess, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, float CallFunc_Conv_FloatToVector_InFloat_ImplicitCast);
	void OnLoaded_D5A0C82B4BA3C329BE0E728CCA761919(class UObject* Loaded);
	void LoadAndPlayEffect(TSoftObjectPtr<class UNiagaraSystem> EffectPath, const struct FTransform& Transform);
	void Initialize();
	void PlayHitEffect(struct FPalDamageInfo& Info);
	void CryCoolTime(enum class EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo);
	void ExecuteUbergraph_BP_HitEffectSlot(int32 EntryPoint, class UObject* Temp_object_Variable, class UNiagaraSystem* K2Node_DynamicCast_AsNiagara_System, bool K2Node_DynamicCast_bSuccess, class UObject* K2Node_CustomEvent_Loaded, TSoftObjectPtr<class UNiagaraSystem> K2Node_CustomEvent_EffectPath, const struct FTransform& K2Node_CustomEvent_Transform, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, class UNiagaraComponent* CallFunc_SpawnSystemAtLocation_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, const struct FPalDamageInfo& K2Node_Event_info, int32 CallFunc_Array_AddUnique_ReturnValue, enum class EAkCallbackType K2Node_CustomEvent_CallbackType, class UAkCallbackInfo* K2Node_CustomEvent_CallbackInfo, bool CallFunc_EqualEqual_ByteByte_ReturnValue, bool CallFunc_SpawnSpecializationEffect_Played, bool CallFunc_SpawnSpecializationEffect_Played_1, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_EqualEqual_ByteByte_ReturnValue_1);
};

}


