#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x25 (0x540 - 0x51B)
// BlueprintGeneratedClass BP_MonsterAIController_BaseCamp.BP_MonsterAIController_BaseCamp_C
class ABP_MonsterAIController_BaseCamp_C : public ABP_MonsterAIControllerBase_C
{
public:
	uint8                                        Pad_3313[0x5];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x520(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                               SpawnedPosition;                                   // 0x528(0x18)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class ABP_MonsterAIController_BaseCamp_C* GetDefaultObj();

	TSubclassOf<class UPalAIControllerWorkerModule> GetWorkerModuleClass();
	class UPalAIActionBase* SetBaseCampActionByClass(TSubclassOf<class UPalAIActionBase> ActionClass, class UPalAIActionBase* CallFunc_SpawnObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, enum class EAIRequestPriority CallFunc_GetRequestPriority_ReturnValue);
	class UPalAIActionBaseCampSleep* SetBaseCampActionSleep(class UPalAIActionBase* CallFunc_SetBaseCampActionByClass_ReturnValue, class UBP_AIActionBaseCamp_Sleep_C* K2Node_DynamicCast_AsBP_AIAction_Base_Camp_Sleep, bool K2Node_DynamicCast_bSuccess);
	void TerminateBaseCampActionByClass_Internal(class UClass* ActionClass, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess);
	void SetAction_Internal(class UPalAIActionComponent* AIActionComponent, class UPalAIActionBaseCampBase* NewAction, enum class EAIRequestPriority CallFunc_GetRequestPriority_ReturnValue);
	void SetAction_SpawningForWorker(class UBP_AIAction_BaseCampSpawningForWorker_C* CallFunc_SpawnObject_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess);
	void FindFixedAssignableObject(const struct FGuid& WorkId, double Range, bool* bFound, TScriptInterface<class IPalBaseCampAssignableObjectInterface>* FoundObject, class UPalIndividualCharacterHandle* IndividualHandle, class UPalBaseCampModel* BaseCamp, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue_1, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_1, float CallFunc_GetRadius_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue_2, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, TScriptInterface<class IPalBaseCampAssignableObjectInterface> CallFunc_FindNearestAssignableObject_FoundObject, bool CallFunc_FindNearestAssignableObject_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FGuid& CallFunc_GetBaseCampId_Base_Camp_Id, class UPalWorkBase* CallFunc_FindWorkAssignableObject_FoundObject, bool CallFunc_FindWorkAssignableObject_ReturnValue, class UPalBaseCampManager* CallFunc_GetBaseCampManager_ReturnValue, class UPalBaseCampModel* CallFunc_TryGetModel_OutModel, bool CallFunc_TryGetModel_ReturnValue, double CallFunc_Add_DoubleDouble_B_ImplicitCast, float CallFunc_FindNearestAssignableObject_Range_ImplicitCast);
	void FailedFixedAssign(class UPalCharacterParameterComponent* CharacterParameter, class APawn* CallFunc_K2_GetPawn_ReturnValue, class APalNetworkTransmitter* CallFunc_GetNetworkTransmitter_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalNetworkBaseCampComponent* CallFunc_GetBaseCamp_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalAIActionCompositeBase* CallFunc_SetAction_BaseCamp_Worker_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UPalAIActionCompositeWorker* K2Node_DynamicCast_AsPal_AIAction_Composite_Worker, bool K2Node_DynamicCast_bSuccess, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, const struct FPalMonsterControllerBaseCampLogContent& K2Node_MakeStruct_PalMonsterControllerBaseCampLogContent);
	class UPalAIActionCompositeBase* SetCompositeActionBaseCamp(class UClass* CompositeActionClass, class UPalAIActionComponent* AIActionComp, class UPalAIActionComponent* CallFunc_GetAIActionComponent_ReturnValue, class UBP_AIActionComposite_BaseCamp_C* CallFunc_SpawnObject_ReturnValue, class UPalAIActionCompositeBase* CallFunc_GetCompositeRoot_ReturnValue, class UClass* CallFunc_GetObjectClass_ReturnValue, bool CallFunc_ClassIsChildOf_ReturnValue, class UPalAIActionCompositeBase* CallFunc_GetCompositeRoot_ReturnValue_1, class UPalAIActionCompositeBase* CallFunc_SpawnObject_ReturnValue_1);
	void GetBaseCampId(struct FGuid* Base_Camp_Id, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, const struct FGuid& CallFunc_GetBaseCampId_ReturnValue);
	void SetAction_WorkerEvent(class UPalAIActionBase* Action, enum class EAIRequestPriority Priority, class UPalAIActionComponent* CallFunc_GetAIActionComponent_ReturnValue);
	void SetAction_Sleep(class UBP_AIActionBaseCamp_Sleep_C* CallFunc_SpawnObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess);
	void SetAction_SleepActively(struct FPalAIActionBaseCampSleepActivelyParameter& Parameter, class UBP_AIActionBaseCamp_SleepActively_C* CallFunc_SpawnObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess);
	void SetAction_RecoverHungry(const struct FPalMonsterControllerBaseCampHungryParameter& Parameter, class UPalAIActionBaseCampBase** Action, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_Action, const struct FPalMonsterControllerBaseCampHungryParameter& CallFunc_SetHungryParameterToDefault_ReturnValue, class UPalAIActionBaseCampRecoverHungry* K2Node_DynamicCast_AsPal_AIAction_Base_Camp_Recover_Hungry, bool K2Node_DynamicCast_bSuccess);
	void NotifyOrderCommandToCurrentRootAction(enum class EPalMapBaseCampWorkerOrderType OrderType, class APawn* CallFunc_K2_GetPawn_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalAIActionCompositeBase* CallFunc_GetCompositeRoot_ReturnValue, class UPalAIActionCompositeBaseCamp* K2Node_DynamicCast_AsPal_AIAction_Composite_Base_Camp, bool K2Node_DynamicCast_bSuccess_1);
	void SetAction_BaseCamp_FighterGunner(class UPalAIActionBaseCampBase** Action, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_Action);
	void SetAction_BaseCamp_Fighter(class UPalAIActionBaseCampBase** Action, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_Action);
	void SetAction_BaseCamp_Fighter_ByDefenseType(enum class EPalMapObjectDefenseType DefenseType, class UPalAIActionBaseCampFighter** FighterAction, class UPalAIActionBaseCampBase* Action, class UPalAIActionBaseCampFighter* K2Node_DynamicCast_AsPal_AIAction_Base_Camp_Fighter, bool K2Node_DynamicCast_bSuccess, bool K2Node_SwitchEnum_CmpSuccess, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_FighterGunner_Action, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_Fighter_Action);
	class UPalAIActionCompositeBase* SetAction_BaseCamp_Worker(class UPalAIActionCompositeWorker* CompositeAction, class UPalAIActionCompositeBase* CallFunc_SetCompositeActionBaseCamp_ReturnValue);
	void SetAction_WithFixAssignRange(struct FGuid& TargetWorkProgressId, double Range, TScriptInterface<class IPalBaseCampAssignableObjectInterface> FoundAssignableObject, class UPalIndividualCharacterSlot* NewLocalVar_0, class UPalBaseCampModel* BaseCamp, class UPalAIActionCompositeBase* CallFunc_SetAction_BaseCamp_Worker_ReturnValue, bool CallFunc_FindFixedAssignableObject_bFound, TScriptInterface<class IPalBaseCampAssignableObjectInterface> CallFunc_FindFixedAssignableObject_FoundObject, class UPalAIActionCompositeWorker* K2Node_DynamicCast_AsPal_AIAction_Composite_Worker, bool K2Node_DynamicCast_bSuccess, TScriptInterface<class IPalMapObjectModelInterface> CallFunc_ToMapObjectModel_ReturnValue, class UPalWorkBase* K2Node_DynamicCast_AsPal_Work_Base, bool K2Node_DynamicCast_bSuccess_1, const struct FGuid& CallFunc_GetModelId_ReturnValue, const struct FGuid& CallFunc_GetWorkId_ReturnValue, enum class EPalBaseCampAssignType CallFunc_GetAssignType_ReturnValue, bool K2Node_SwitchEnum_CmpSuccess, class UPalAIActionCompositeBase* CallFunc_SetAction_BaseCamp_Worker_ReturnValue_1, class UPalAIActionCompositeWorker* K2Node_DynamicCast_AsPal_AIAction_Composite_Worker_1, bool K2Node_DynamicCast_bSuccess_2);
	void SetAction_BaseCamp(class UClass* AIActionClass, enum class EAIRequestPriority Priority, class UPalAIActionBaseCampBase** Action, class UPalAIActionComponent* CallFunc_GetAIActionComponent_ReturnValue, class UPalAIActionBaseCampBase* CallFunc_SpawnObject_ReturnValue);
	void SetAction_DefaultPos(class UPalAIActionComponent* ActionComp, class UPalBaseCampManager* CallFunc_GetBaseCampManager_ReturnValue, const struct FGuid& CallFunc_GetBaseCampId_Base_Camp_Id, class UPalBaseCampModel* CallFunc_TryGetModel_OutModel, bool CallFunc_TryGetModel_ReturnValue, class UBP_AIAction_ReturnToDefaultPosition_C* CallFunc_SpawnObject_ReturnValue, float CallFunc_GetRange_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, double CallFunc_Setup_MoveEndDistance_ImplicitCast);
	void SetAction_Liftup(class UPalAIActionLiftup* CallFunc_SpawnObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess, bool CallFunc_K2_PushAction_ReturnValue);
	void SetAction_CapturedStorage(class UBP_AIAction_WanderingCage_C* CallFunc_SpawnObject_ReturnValue, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess);
	void SetCapturedStorageAction();
	void SetBaseCampAction();
	void SetBaseCampFighterAction();
	void SetBaseCampActionWithFixAssign(struct FGuid& TargetWorkProgressId, float DistanceFixAssignTargetting);
	void NotifyOrderCommand(enum class EPalMapBaseCampWorkerOrderType OrderType);
	void ReceivePossess(class APawn* PossessedPawn);
	void InterruptReturnBackToBaseCamp();
	void SetBaseCampFighterGunnerAction();
	void OnDeadDelegate______0(const struct FPalDeadInfo& DeadInfo);
	void InterruptRecoverHungryAction(const struct FPalMonsterControllerBaseCampHungryParameter& Parameter);
	void SetDefaultPositionAction();
	void SetBaseCampActionSleepMedicalBed(struct FGuid& TargetBedConcreteModelId);
	void InterruptPlayWorkerEventAction(class UPalAIActionBase* Action, enum class EAIRequestPriority Priority);
	void SetBaseCampActionLift();
	void ShowBaseCampLog(struct FPalMonsterControllerBaseCampLogContent& Content);
	void SetBaseCampActionSpawningForWork();
	void InterruptSleepActivelyAction(struct FPalAIActionBaseCampSleepActivelyParameter& Parameter);
	void TerminateBaseCampActionByClass(TSubclassOf<class UPalAIActionBase> ActionClass);
	void ExecuteUbergraph_BP_MonsterAIController_BaseCamp(int32 EntryPoint, TSubclassOf<class UPalAIActionBase> K2Node_Event_ActionClass, TArray<class AActor*>& Temp_object_Variable, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APawn* CallFunc_K2_GetPawn_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue_1, class APawn* CallFunc_K2_GetPawn_ReturnValue_1, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue_1, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, const struct FGuid& K2Node_Event_TargetWorkProgressId, float K2Node_Event_DistanceFixAssignTargetting, class UPalAIActionCompositeBase* CallFunc_SetAction_BaseCamp_Worker_ReturnValue, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_Fighter_Action, enum class EPalMapBaseCampWorkerOrderType K2Node_Event_OrderType, class APawn* K2Node_Event_PossessedPawn, class UPalAIActionBaseCampBase* CallFunc_SetAction_BaseCamp_FighterGunner_Action, class APawn* CallFunc_K2_GetPawn_ReturnValue_2, const struct FPalDeadInfo& K2Node_CustomEvent_DeadInfo, class UPalDamageReactionComponent* CallFunc_GetComponentByClass_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_1, const struct FPalMonsterControllerBaseCampHungryParameter& K2Node_Event_Parameter_1, class UPalAIActionBaseCampBase* CallFunc_SetAction_RecoverHungry_Action, const struct FGuid& K2Node_Event_TargetBedConcreteModelId, class UPalAIActionBase* K2Node_Event_Action, enum class EAIRequestPriority K2Node_Event_Priority, const struct FPalMonsterControllerBaseCampLogContent& K2Node_Event_Content, const struct FPalAIActionBaseCampSleepActivelyParameter& K2Node_Event_Parameter, double CallFunc_SetAction_WithFixAssignRange_Range_ImplicitCast);
};

}


