#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x70 (0x188 - 0x118)
// BlueprintGeneratedClass BP_OtomoPalHolderComponent.BP_OtomoPalHolderComponent_C
class UBP_OtomoPalHolderComponent_C : public UPalOtomoHolderComponentBase
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x118(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                        ActivatedOtomoSlotID;                              // 0x120(0x4)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                        SelectedOtomoSlotID;                               // 0x124(0x4)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	FMulticastInlineDelegateProperty_            OnChangedSelectOtomoIndexEvent;                    // 0x128(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            OnActivateOtomo;                                   // 0x138(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            OnUsedActiveSkill;                                 // 0x148(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	FMulticastInlineDelegateProperty_            OnInactiveOtomoEvent;                              // 0x158(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UPalIndividualCharacterHandle*         ActivatedHandle;                                   // 0x168(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UClass*                                AiClass;                                           // 0x170(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class APalCharacter*>                 ReservePalLocationList;                            // 0x178(0x10)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

	static class UClass* StaticClass();
	static class UBP_OtomoPalHolderComponent_C* GetDefaultObj();

	void SetOtomoInvokerDisable(class AActor* Otomo, bool IsDisable, class UPalNavigationInvokerComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Update_Reserve_Pal_Location(double DeltaTime, class AActor* CallFunc_GetOwner_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_HasAuthority_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class APalCharacter* CallFunc_GetOwnerCharacter_Character, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, double CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double CallFunc_BreakVector_Z, double CallFunc_Add_DoubleDouble_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, const struct FVector& CallFunc_MakeVector_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FHitResult& CallFunc_K2_SetActorLocation_SweepHitResult, bool CallFunc_K2_SetActorLocation_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue);
	void IncrementActiveOtomoCount(class UPalPlayerRecordData* PlayerRecordData, class FName CharacterID);
	void GetNextValidSlotIndex();
	bool IsValidCurrentSelectPalActor(class APalCharacter* CallFunc_TryGetCurrentSelectPalActor_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	class APalCharacter* TryGetCurrentSelectPalActor(class APalCharacter* CallFunc_TryGetOtomoActorBySlotIndex_ReturnValue);
	void SetTrainer(class APalCharacter* Character, class AActor* CallFunc_GetOwner_ReturnValue, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, class APalCharacter* CallFunc_GetDefaultPlayerCharacter_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsControlledByPlayer_ReturnValue);
	void RemovePalFromParty(class UPalIndividualCharacterHandle* RemoveHandle, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UPalIndividualCharacterSlot*>& CallFunc_GetSlots_Slots, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterSlot* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, const struct FPalCharacterSlotId& CallFunc_GetSlotId_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetHandle_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
	void GetOwnerCharacter(class APalCharacter** Character, class AActor* CallFunc_GetOwner_ReturnValue, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess, class APawn* CallFunc_K2_GetPawn_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess_1);
	void FindNearstEnemy(const struct FVector& Location, class AActor** Actor, class APalCharacter* CallFunc_GetEnemyWhenOtomoThrow_ReturnValue);
	void ActivateCurrentOtomoFromBall(const struct FTransform& BallTransform, class AActor* BallHitActor);
	bool ActivateCurrentOtomoNearThePlayer(const struct FTransform& CallFunc_GetTransform_SpawnPalNearTrainer_ReturnValue, bool CallFunc_ActivateCurrentOtomo_ReturnValue);
	bool ActivateCurrentOtomo(const struct FTransform& SpawnTransform, bool CallFunc_Inactivate_Otomo_isSuccess, bool CallFunc_IsRidingByOtomoSlotID_isRiding, bool CallFunc_ActivateOtomo_isSuccess, bool CallFunc_NotEqual_IntInt_ReturnValue);
	int32 GetSpawnedOtomoID();
	void TryFixAssignNearestWorkSelectedOtomo(class AActor* HitActor, class APalCharacter* CallFunc_TryGetOtomoActorBySlotIndex_ReturnValue, class AController* CallFunc_GetController_ReturnValue, bool CallFunc_IsValid_ReturnValue, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess, class UPalAIActionComponent* K2Node_DynamicCast_AsPal_AIAction_Component, bool K2Node_DynamicCast_bSuccess_1, class UPalAIActionCompositeBase* CallFunc_GetCompositeRoot_ReturnValue, class UPalAIActionOtomoDefault* K2Node_DynamicCast_AsPal_AIAction_Otomo_Default, bool K2Node_DynamicCast_bSuccess_2);
	void SetSelectOtomoID_Internal(int32 Index);
	void DecrementSelectOtomoID_Internal(int32 Temp_int_Variable, int32 Temp_int_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_GetMaxOtomoNum_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsALLEmpty_ReturnValue, int32 CallFunc_GetSelectedOtomoID_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_GetMaxOtomoNum_ReturnValue_1, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_EqualEqual_IntInt_ReturnValue);
	void IncrementSelectOtomoID_Internal(int32 TempStartIndex, int32 Temp_int_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, int32 Temp_int_Variable_1, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_GetMaxOtomoNum_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 CallFunc_GetMaxOtomoNum_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue);
	void InactiveActor(class APalCharacter* Actor, bool StayVisible, bool* IsSuccess, class AController* CallFunc_GetController_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess_1);
	void InitializeSlot();
	bool IsActivatedSelectOtomo(bool CallFunc_EqualEqual_IntInt_ReturnValue);
	int32 GetMaxOtomoNum();
	int32 GetPreviousOtomoSlotID(int32 WorkIndex, int32 StartIndex, int32 Temp_int_Variable, int32 Temp_int_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 CallFunc_GetMaxOtomoNum_ReturnValue, bool CallFunc_IsALLEmpty_ReturnValue, int32 CallFunc_Subtract_IntInt_ReturnValue_1, bool CallFunc_LessEqual_IntInt_ReturnValue);
	int32 GetNextOtomoSlotID(int32 TempWorkIndex, int32 TempStartIndex, int32 CalcSlotID, bool IsLoop, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_GetMaxOtomoNum_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Subtract_IntInt_ReturnValue, int32 Temp_int_Variable_1, int32 CallFunc_GetMaxOtomoNum_ReturnValue_1, int32 CallFunc_Percent_IntInt_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	int32 GetSelectedOtomoID();
	bool IsRidingBySelectSlotID(int32 CallFunc_GetSelectedOtomoID_ReturnValue, bool CallFunc_IsRidingByOtomoSlotID_isRiding);
	bool IsRidingBySpawnSlotID(bool CallFunc_IsRidingByOtomoSlotID_isRiding);
	void CallCancelCommand(int32 CallFunc_GetSelectedOtomoID_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, class AController* CallFunc_GetController_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess_1, class UPalAIActionComponent* CallFunc_GetAIActionComponent_ReturnValue, enum class EPalAIActionCategory CallFunc_GetCurrentAIActionCategory_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void CoopCallCommand(int32 SlotID, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess, bool CallFunc_GreaterEqual_IntInt_ReturnValue, class UPalAIActionComponent* CallFunc_GetAIActionComponent_ReturnValue, enum class EPalAIActionCategory CallFunc_GetCurrentAIActionCategory_ReturnValue, bool CallFunc_EqualEqual_ByteByte_ReturnValue);
	void Dummy_Despawn_Callback(const struct FPalInstanceID& ID);
	void Try_Get_Current_Active_Pal_Actor(class APalCharacter** Otomo, class APalCharacter* CallFunc_TryGetSpawnedOtomo_ReturnValue);
	void ActiveAndAttackCurrentPal(class AActor* Target, class APalCharacter* CallFunc_TryGetOtomoActorBySlotIndex_ReturnValue, class AController* CallFunc_GetController_ReturnValue, bool CallFunc_IsValid_ReturnValue, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess);
	void Update_Otomo_Slot_in_Local(int32 SlotIndex, class UPalIndividualCharacterHandle* LastHandle);
	void Update_Otomo_Slot_In_Server(int32 SlotIndex, class UPalIndividualCharacterHandle* LastHandle, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, bool CallFunc_Inactivate_Otomo_By_Handle_isSuccess, bool CallFunc_EqualEqual_IntInt_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void Inactivate_Otomo_By_Handle(class UPalIndividualCharacterHandle* IndividualHandle, bool* IsSuccess, class APalCharacter* TempOtomoActor, class UPalAbilitySkillParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsCooping_ReturnValue, class UPalPartnerSkillParameterComponent* CallFunc_GetComponentByClass_ReturnValue_1, bool CallFunc_GetActiveActorFlag_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, bool CallFunc_BooleanOR_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FTransform& CallFunc_MakeTransform_ReturnValue, bool CallFunc_InactiveActor_isSuccess, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_ReturnPalEffect_C* CallFunc_FinishSpawningActor_ReturnValue, class APalCharacter* CallFunc_TryGetOwnerControlledCharacter_ReturnValue, bool CallFunc_IsValid_ReturnValue_3);
	void Inactivate_Otomo(bool* IsSuccess, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_Inactivate_Otomo_By_Handle_isSuccess);
	void ActivateOtomo(int32 SlotID, const struct FTransform& StartTransform, bool* IsSuccess, class APalCharacter* TempPal, bool IsDead, double TempAngle, class APalCharacter* Trainer, class UPalAbilitySkillParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Array_RemoveItem_ReturnValue, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue_1, class AController* CallFunc_GetController_ReturnValue, class UPalAIActionComponent* CallFunc_GetComponentByClass_ReturnValue_2, class AController* CallFunc_GetController_ReturnValue_1, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, class UPalVisualEffectBase* CallFunc_AddVisualEffectForActor_ReturnValue, class ABP_MonsterAIController_NPCOtomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_NPCOtomo, bool K2Node_DynamicCast_bSuccess_1, class ABP_MonsterAIControllerBase_C* K2Node_DynamicCast_AsBP_Monster_AIController_Base, bool K2Node_DynamicCast_bSuccess_2, class UPalPartnerSkillParameterComponent* CallFunc_GetComponentByClass_ReturnValue_3, bool CallFunc_IsLive_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_4, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess_3, class APalPlayerState* CallFunc_GetPalPlayerState_ReturnValue, bool CallFunc_IsDead_ReturnValue, class UPalPlayerRecordData* CallFunc_GetRecordData_ReturnValue, bool CallFunc_IsValid_ReturnValue_3, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsControlledByPlayer_ReturnValue, class UPalIndividualCharacterParameter* CallFunc_TryGetIndividualParameter_ReturnValue, bool CallFunc_IsValid_ReturnValue_4, class FName CallFunc_GetCharacterID_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue_1, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_5, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_6, class AActor* CallFunc_GetOwner_ReturnValue_1, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess_4, class APawn* CallFunc_K2_GetPawn_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess_5);
	void IsRidingByOtomoSlotID(int32 SlotID, bool* IsRiding, int32 SelectedSlotID, class AActor* ControlledPawn, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class AActor* CallFunc_GetOwner_ReturnValue, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess, class APawn* CallFunc_K2_GetPawn_ReturnValue);
	void Add_Otomo_Down_Log(const struct FPalDeadInfo& Actor, bool CallFunc_IsControlledByPlayer_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_HasAuthority_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_IsValid_ReturnValue, const class FString& CallFunc_GetNickName_outName, class FText CallFunc_Conv_StringToText_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, const struct FFormatArgumentData& K2Node_MakeStruct_FormatArgumentData, TArray<struct FFormatArgumentData>& K2Node_MakeArray_Array, const struct FPalLogAdditionalData& K2Node_MakeStruct_PalLogAdditionalData, class FText CallFunc_CreateLogText_outText, class FText CallFunc_Format_ReturnValue, class UPalLogManager* CallFunc_GetLogManager_ReturnValue, const struct FGuid& CallFunc_AddLog_ReturnValue);
	void FindSlotByIndividualID(const struct FPalInstanceID& ID, int32* SlotID, int32 TempSlotID, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, TArray<class UPalIndividualCharacterSlot*>& CallFunc_GetSlots_Slots, class UPalIndividualCharacterSlot* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetHandle_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_EqualEqual_PalInstanceIDPalInstanceID_ReturnValue);
	void SpawnCharacterCallback(const struct FPalInstanceID& ID, int32 SlotID, class APalCharacter* Trainer, class APalCharacter* TempSpawnedMonster, int32 CallFunc_FindSlotByIndividualID_SlotID, class UPalPartnerSkillParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_IsControlledByPlayer_ReturnValue, class AController* K2Node_DynamicCast_AsController, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsControlledByPlayer_ReturnValue_1, bool CallFunc_IsControlledByPlayer_ReturnValue_2, class UPalRideMarkerComponent* CallFunc_GetComponentByClass_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue_1, class UPalIndividualCharacterParameter* CallFunc_TryGetIndividualParameter_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class UPalNavigationInvokerComponent* CallFunc_GetComponentByClass_ReturnValue_2, bool CallFunc_IsValid_ReturnValue_3, class AController* CallFunc_GetController_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo, bool K2Node_DynamicCast_bSuccess_2, int32 CallFunc_Array_AddUnique_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue_3, class AActor* CallFunc_AdjustActorToFloor_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue_1, class AController* K2Node_DynamicCast_AsController_1, bool K2Node_DynamicCast_bSuccess_3, class APawn* CallFunc_K2_GetPawn_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess_4, class ABP_MonsterAIController_Otomo_C* K2Node_DynamicCast_AsBP_Monster_AIController_Otomo_1, bool K2Node_DynamicCast_bSuccess_5, bool CallFunc_GreaterEqual_IntInt_ReturnValue, bool CallFunc_IsValid_ReturnValue_4);
	void SpawnOtomo(int32 SlotID, double TempAngle, class APalCharacter* Trainer, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UPalIndividualCharacterHandle* CallFunc_GetOtomoIndividualHandle_ReturnValue, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, bool CallFunc_IsValid_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, const struct FNetworkActorSpawnParameters& K2Node_MakeStruct_NetworkActorSpawnParameters);
	void ActivateCurrentOtomoFromBall_ToServer(const struct FTransform& BallTransform, class AActor* HitActor);
	void SetActivateOtomoID_ToALL(int32 ID);
	void CallOnActivateOtomo_ToALL();
	void CallOnInactivateOtomo_ToALL();
	void SetLocationOtomoForActive_ToAll(class AActor* Otomo, const struct FTransform& TF);
	void ReceiveEndPlay(enum class EEndPlayReason EndPlayReason);
	void UpdateSlot(int32 SlotIndex, class UPalIndividualCharacterHandle* LastHandle);
	void Otomo_DeathEvent(const struct FPalDeadInfo& DeadInfo);
	void InactivateCurrentOtomo();
	void Setup();
	void Setup_ToServer();
	void UpdateSlotInServer(int32 SlotIndex, class UPalIndividualCharacterHandle* LastHandle);
	void SpawnOtomoByLoad(int32 SlotIndex);
	void ReceiveTick(float DeltaSeconds);
	void DelayAddOtomoForReserverList(class APalCharacter* Otomo);
	void ExecuteUbergraph_BP_OtomoPalHolderComponent(int32 EntryPoint, class UPalTutorialManager* CallFunc_GetTutorialManager_ReturnValue, const struct FTransform& K2Node_CustomEvent_BallTransform, class AActor* K2Node_CustomEvent_HitActor, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale, bool CallFunc_ActivateCurrentOtomo_ReturnValue, class AActor* CallFunc_FindNearstEnemy_Actor, bool CallFunc_IsValid_ReturnValue, int32 K2Node_CustomEvent_ID, class APalCharacter* CallFunc_TryGetCurrentSelectPalActor_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class UPalGameSetting* CallFunc_GetGameSetting_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, class AActor* K2Node_CustomEvent_Otomo_1, const struct FTransform& K2Node_CustomEvent_TF, enum class EEndPlayReason K2Node_Event_EndPlayReason, const struct FHitResult& CallFunc_K2_SetActorTransform_SweepHitResult, bool CallFunc_K2_SetActorTransform_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, int32 K2Node_CustomEvent_slotIndex_1, class UPalIndividualCharacterHandle* K2Node_CustomEvent_LastHandle_1, const struct FPalDeadInfo& K2Node_CustomEvent_DeadInfo, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess_1, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_Inactivate_Otomo_isSuccess, bool CallFunc_IsValid_ReturnValue_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, bool CallFunc_Inactivate_Otomo_isSuccess_1, int32 K2Node_CustomEvent_slotIndex, class UPalIndividualCharacterHandle* K2Node_CustomEvent_LastHandle, int32 K2Node_Event_slotIndex, float K2Node_Event_DeltaSeconds, class APalCharacter* K2Node_CustomEvent_Otomo, int32 CallFunc_Array_AddUnique_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, double CallFunc_Update_Reserve_Pal_Location_DeltaTime_ImplicitCast);
	void OnInactiveOtomoEvent__DelegateSignature();
	void OnUsedActiveSkill__DelegateSignature();
	void OnActivateOtomo__DelegateSignature();
	void OnChangedSelectOtomoIndexEvent__DelegateSignature();
};

}


