#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0xD (0x5D - 0x50)
// BlueprintGeneratedClass BP_PalIncidentRandomActionHunterVsPal.BP_PalIncidentRandomActionHunterVsPal_C
class UBP_PalIncidentRandomActionHunterVsPal_C : public UBP_PalIncidentRandomActionBase_C
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x50(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                        WinnerGroup;                                       // 0x58(0x4)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsAllNpcSpawned;                                   // 0x5C(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_PalIncidentRandomActionHunterVsPal_C* GetDefaultObj();

	void ExistsAliveCharacter(TArray<class APalCharacter*>& Array, bool* NewParam, int32 CallFunc_Array_Length_ReturnValue, int32 Temp_int_Array_Index_Variable, class APalCharacter* CallFunc_Array_Get_Item, bool CallFunc_IsDead_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue);
	void GetSpawnedLocation(class APalAIController* Controller, bool* Found, struct FVector* Location, bool CallFunc_IsValid_ReturnValue, class APawn* CallFunc_K2_GetPawn_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class APalRandomIncidentNPCSpawner* CallFunc_GetSpawner_Spawmer, class ABP_PalRandomIncidentNPCSpawner_C* K2Node_DynamicCast_AsBP_Pal_Random_Incident_NPCSpawner, bool K2Node_DynamicCast_bSuccess, bool CallFunc_GetSpawnedLocation_Found, const struct FVector& CallFunc_GetSpawnedLocation_SpawnedLocation);
	void GetSpawnRadius(double* Radius, class APalRandomIncidentNPCSpawner* CallFunc_GetSpawner_Spawmer, class AActor* CallFunc_GetOwner_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalRandomIncidentSpawnerBase* K2Node_DynamicCast_AsPal_Random_Incident_Spawner_Base, bool K2Node_DynamicCast_bSuccess, float CallFunc_GetAreaRadius_ReturnValue, double K2Node_FunctionResult_Radius_ImplicitCast);
	void GetSpawnerLocation(struct FVector* Location, class APalRandomIncidentNPCSpawner* CallFunc_GetSpawner_Spawmer, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void ResetAIController_Monster(class ABP_MonsterAIControllerBase_C* Controller, class APawn* CallFunc_K2_GetPawn_ReturnValue, bool CallFunc_GetSpawnedLocation_Found, const struct FVector& CallFunc_GetSpawnedLocation_Location, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_GetSpawnerLocation_Location, TScriptInterface<class IBPI_GetPalAIBlackboard_C> K2Node_DynamicCast_AsBPI_Get_Pal_AIBlackboard, bool K2Node_DynamicCast_bSuccess, double CallFunc_GetSpawnRadius_Radius, class UBP_PalAIBlackboard_Common_C* CallFunc_GetMyBB_PalBrackboard, class UPalAIActionComponent* CallFunc_GetComponentByClass_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue);
	void ResetAIController_NPC(class ABP_NPCAIController_C* Controller, bool CallFunc_GetSpawnedLocation_Found, const struct FVector& CallFunc_GetSpawnedLocation_Location, class APawn* CallFunc_K2_GetPawn_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_GetSpawnerLocation_Location, double CallFunc_GetSpawnRadius_Radius, TScriptInterface<class IBPI_GetPalAIBlackboard_C> CallFunc_GetMyBB_self_CastInput, class UBP_PalAIBlackboard_Common_C* CallFunc_GetMyBB_PalBrackboard, class UPalAIActionComponent* CallFunc_GetComponentByClass_ReturnValue, class AActor* CallFunc_GetOwner_ReturnValue);
	void ResetAIController(int32 GroupID, class AActor* Actor, class AController* Controller, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class AController* CallFunc_GetController_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class ABP_MonsterAIController_Wild_C* K2Node_DynamicCast_AsBP_Monster_AIController_Wild, bool K2Node_DynamicCast_bSuccess, class ABP_NPCAIController_C* K2Node_DynamicCast_AsBP_NPCAIController, bool K2Node_DynamicCast_bSuccess_1, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_MatchCharacters, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_UnmatchCharacters, int32 CallFunc_Array_Length_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue);
	void GetWinnerGroup(int32* GroupID, bool IsAnyNpcAlive, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<int32>& CallFunc_CollectGroupIds_GroupIds, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_MatchCharacters, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_UnmatchCharacters, bool CallFunc_ExistsAliveCharacter_NewParam, bool CallFunc_ExistsAliveCharacter_NewParam_1, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_BooleanAND_ReturnValue);
	void Set_Hate_To_Targets(class APalCharacter* Character, TArray<class APalCharacter*>& Targets, class APalAIController* Controller, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UPalGameSetting* CallFunc_GetGameSetting_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item, class APalCharacter* CallFunc_Array_Get_Item_1, class APalCharacter* CallFunc_Array_Get_Item_2, int32 CallFunc_Array_Length_ReturnValue, class UPalCharacterParameterComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FFixedPoint64& CallFunc_GetMaxHP_ReturnValue, float CallFunc_Convert_FixedPoint64ToFloat_ReturnValue, double CallFunc_Multiply_DoubleDouble_ReturnValue, class AAIController* CallFunc_GetAIController_ReturnValue, class ABP_MonsterAIController_Wild_C* K2Node_DynamicCast_AsBP_Monster_AIController_Wild, bool K2Node_DynamicCast_bSuccess, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess_1, class ABP_NPCAIController_C* K2Node_DynamicCast_AsBP_NPCAIController, bool K2Node_DynamicCast_bSuccess_2, class UPalHate* CallFunc_GetHateSystem_ReturnValue, double CallFunc_Multiply_DoubleDouble_B_ImplicitCast, double CallFunc_Multiply_DoubleDouble_A_ImplicitCast, float CallFunc_ChangeHate_PlusHateValue_ImplicitCast);
	void CollectCharactersByGroup(int32 Group, TArray<class APalCharacter*>* MatchCharacters, TArray<class APalCharacter*>* UnmatchCharacters, class APalRandomIncidentNPCSpawner* Spawner, class FName RowName, class UDataTable* NPCData, class UDataTable* MonstarData, const TArray<class APalCharacter*>& UnmatchList, const TArray<class APalCharacter*>& MatchList, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, class APalRandomIncidentNPCSpawner* CallFunc_GetSpawner_Spawmer, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_GetSettingTableRow_Result, const struct FPalRandomIncidentSettings& CallFunc_GetSettingTableRow_Data, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, const struct FPalRandomIncidentSpawnNPCData& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, class FName CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_EqualEqual_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* CallFunc_FindCharacterByName_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1, class APalCharacter* CallFunc_FindCharacterByName_ReturnValue_1, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, int32 CallFunc_Array_Add_ReturnValue_2, int32 CallFunc_Array_Add_ReturnValue_3, bool CallFunc_EqualEqual_IntInt_ReturnValue_1, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames_1, class FName CallFunc_Array_Get_Item_1, bool CallFunc_IsValid_ReturnValue_2, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void CollectGroupIds(TArray<int32>* GroupIds, class FName RowName, class UDataTable* NPCData, class UDataTable* MonstarData, const TArray<int32>& ReVal, int32 Temp_int_Loop_Counter_Variable, int32 Temp_int_Array_Index_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Loop_Counter_Variable_1, int32 CallFunc_Add_IntInt_ReturnValue_1, int32 Temp_int_Array_Index_Variable_1, bool CallFunc_GetSettingTableRow_Result, const struct FPalRandomIncidentSettings& CallFunc_GetSettingTableRow_Data, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, class FName CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FPalRandomIncidentSpawnNPCData& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_IsValid_ReturnValue, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames_1, class FName CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Add_ReturnValue_1, bool CallFunc_Array_Contains_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, bool CallFunc_IsValid_ReturnValue_1);
	void SetHate(int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, TArray<int32>& CallFunc_CollectGroupIds_GroupIds, int32 CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_MatchCharacters, TArray<class APalCharacter*>& CallFunc_CollectCharactersByGroup_UnmatchCharacters, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1);
	void OnAllNpcSpawned();
	void OnInitialized();
	void OnStart();
	void OnTerminate();
	void OnTick(float DeltaTime);
	void ExecuteUbergraph_BP_PalIncidentRandomActionHunterVsPal(int32 EntryPoint, bool CallFunc_GreaterEqual_IntInt_ReturnValue, float K2Node_Event_DeltaTime, int32 CallFunc_GetWinnerGroup_GroupId, bool CallFunc_Less_IntInt_ReturnValue);
};

}


