#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x72 (0x1D2 - 0x160)
// BlueprintGeneratedClass BP_PalIncidentNPCTalk.BP_PalIncidentNPCTalk_C
class UBP_PalIncidentNPCTalk_C : public UBP_PalIncidentBase_C
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x160(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class UDataTable*                            TalkData;                                          // 0x168(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	struct FGuid                                 ShopID;                                            // 0x170(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash)
	class UPalNPCMultiTalkHandle*                MultiTalkHandle;                                   // 0x180(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                         IsTalking;                                         // 0x188(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                         IsShopping;                                        // 0x189(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_132A[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class ABP_PalIncidentCamera_C*               Camera;                                            // 0x190(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AActor*                                PlayerViewTarget;                                  // 0x198(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FString                                TalkSequence;                                      // 0x1A0(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                         IsDelayFinish;                                     // 0x1B0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                        Pad_132C[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       DelayFinishElapsedTime;                            // 0x1B8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPalHUDDispatchParameterBase*          ItemShopHUDParameter;                              // 0x1C0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UPalHUDDispatchParameterBase*          PalShopHUDParameter;                               // 0x1C8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	enum class E_PalItemShopTabType              OpenItemShopTabType;                               // 0x1D0(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	enum class E_PalItemShopTabType              OpenPalShopTabType;                                // 0x1D1(0x1)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

	static class UClass* StaticClass();
	static class UBP_PalIncidentNPCTalk_C* GetDefaultObj();

	void OpenPalShop_Internal(class UPalVenderDataComponent* VenderDataComponent, class UPalShopBase* CallFunc_TryGetPalShop_OutShop, bool CallFunc_TryGetPalShop_ReturnValue, class UPalHUDService* CallFunc_GetHUDService_ReturnValue, class UBP_PalUIDIspatchParameter_PalShop_C* CallFunc_SpawnObject_ReturnValue);
	void OnRegisteredPalShopEvent(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, bool CallFunc_IsValid_ReturnValue, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void OpenItemShop_Internal(class UPalVenderDataComponent* VenderDataComponent, class UPalShopBase* CallFunc_TryGetItemShop_OutShop, bool CallFunc_TryGetItemShop_ReturnValue, class UPalHUDService* CallFunc_GetHUDService_ReturnValue, class UBP_PalUIDispatchParameter_ItemShop_C* CallFunc_SpawnObject_ReturnValue);
	void OnRegisteredItemShopEvent(FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void CunsumeRequestItem(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, int32 RequestNum, int32 ConsumedItemNum, class FName RequestItem, TScriptInterface<class IPalNPCTalkSystemCustomFunctionInterface> Interface, class FText CallFunc_GetItemName_outName, class FText CallFunc_Conv_IntToText_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess, class UPalPlayerInventoryData* CallFunc_GetLocalInventoryData_ReturnValue, int32 CallFunc_RequestConsumeInventoryItem_ReturnValue);
	void Lottery_Index_by_Weights(TArray<double>& Weights, int32* Index, int32 SelectedIndex, double LotteryWeight, double TotalWeight, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, bool Temp_bool_True_if_break_was_hit_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Array_Index_Variable_1, int32 Temp_int_Loop_Counter_Variable_1, double CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, double CallFunc_Subtract_DoubleDouble_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_LessEqual_DoubleDouble_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1, double CallFunc_RandomFloatInRange_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue_1, double CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue_1, double CallFunc_Add_DoubleDouble_ReturnValue);
	void LotteryItemAndNum(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class FName* AddItemName1, int32* AddItemNum1, int32 SelectedIndex, const TArray<double>& Weights, const TArray<class FName>& RowNames, class UDataTable* FuncParameter, int32 AddItemNum, class FName AddItemName, int32 MaxRange, int32 Unit, int32 NumMax, int32 NumMin, int32 MinRange, int32 Temp_int_Array_Index_Variable, int32 CallFunc_RandomIntegerInRange_ReturnValue, int32 CallFunc_Multiply_IntInt_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue, int32 CallFunc_Percent_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, bool CallFunc_NotEqual_IntInt_ReturnValue, int32 CallFunc_Divide_IntInt_ReturnValue_1, bool CallFunc_GreaterEqual_IntInt_ReturnValue, const struct FFPalPresentLotteryDataTableRow& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, int32 CallFunc_Max_ReturnValue, int32 CallFunc_Max_ReturnValue_1, int32 CallFunc_Max_ReturnValue_2, class FName CallFunc_Array_Get_Item, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, const struct FFPalPresentLotteryDataTableRow& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 Temp_int_Loop_Counter_Variable, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue_1);
	void HasRequestItem(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class FName RequestItem, TScriptInterface<class IPalNPCTalkSystemCustomFunctionInterface> Interface, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, bool CallFunc_EqualEqual_NameName_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Not_PreBool_ReturnValue, class UPalPlayerInventoryData* CallFunc_GetLocalInventoryData_ReturnValue, bool CallFunc_IsExistItem_ReturnValue);
	void RequestItem(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, int32 SelectedIndex, const TArray<double>& Weights, class UDataTable* DataTable, const TArray<class FName>& RowNames, TScriptInterface<class IPalNPCTalkSystemCustomFunctionInterface> Interface, int32 Temp_int_Array_Index_Variable, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess, int32 Temp_int_Loop_Counter_Variable, const struct FFPalRequestItemLotteryDataTableRow& CallFunc_GetDataTableRowFromName_OutRow, bool CallFunc_GetDataTableRowFromName_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, class FText CallFunc_Conv_IntToText_ReturnValue, class FText CallFunc_GetItemName_outName, bool CallFunc_GreaterEqual_IntInt_ReturnValue, int32 CallFunc_Lottery_Index_by_Weights_Index, TArray<class FName>& CallFunc_GetDataTableRowNames_OutRowNames, class FName CallFunc_Array_Get_Item, const struct FFPalRequestItemLotteryDataTableRow& CallFunc_GetDataTableRowFromName_OutRow_1, bool CallFunc_GetDataTableRowFromName_ReturnValue_1, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, int32 CallFunc_Array_Add_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue_1, bool CallFunc_IsValid_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk_1, bool K2Node_DynamicCast_bSuccess_1);
	void AddItemToInventory(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, TScriptInterface<class IPalNPCTalkSystemCustomFunctionInterface> Interface, class UPalPlayerInventoryData* CallFunc_GetLocalInventoryData_ReturnValue, class FName CallFunc_LotteryItemAndNum_AddItemName1, int32 CallFunc_LotteryItemAndNum_AddItemNum1);
	void SpawnItem(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, int32 SelectedIndex, const TArray<double>& Weights, const TArray<class FName>& RowNames, class UDataTable* FuncParameter, int32 AddItemNum, class FName AddItemName, int32 MaxRange, int32 Unit, int32 NumMax, int32 NumMin, int32 MinRange, class FName CallFunc_LotteryItemAndNum_AddItemName1, int32 CallFunc_LotteryItemAndNum_AddItemNum1, bool CallFunc_Greater_IntInt_ReturnValue, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FTransform& CallFunc_GetTransform_ReturnValue, const struct FVector& CallFunc_Multiply_VectorVector_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FRotator& CallFunc_BreakTransform_Rotation, const struct FVector& CallFunc_BreakTransform_Scale);
	void ReturnToSpawnedPointSquad(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class AController* CallFunc_GetController_ReturnValue, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess, class UPalSquad* CallFunc_GetSquad_ReturnValue, TArray<struct FPalInstanceID>& CallFunc_GetMemberID_OutList, int32 CallFunc_Array_Length_ReturnValue, const struct FPalInstanceID& CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class UPalIndividualCharacterHandleReference* CallFunc_GetIndividualHandleReference_ReturnValue, bool CallFunc_IsValid_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, class AController* CallFunc_GetController_ReturnValue_1, class ABP_NPCAIController_Visitor_C* K2Node_DynamicCast_AsBP_NPCAIController_Visitor, bool K2Node_DynamicCast_bSuccess_1);
	void ReturnToSpawnedPoint(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class AController* CallFunc_GetController_ReturnValue, class ABP_NPCAIController_Visitor_C* K2Node_DynamicCast_AsBP_NPCAIController_Visitor, bool K2Node_DynamicCast_bSuccess);
	void AttackToPlayer(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class AController* CallFunc_GetController_ReturnValue, class ABP_NPCAIController_C* K2Node_DynamicCast_AsBP_NPCAIController, bool K2Node_DynamicCast_bSuccess_1);
	void OpenPalShop_Sell(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class UPalHUDDispatchParameter_PalShop* TempWidgetParam, class UObject* WidgetParam, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValidPalShop_ReturnValue);
	void Terminate(bool CallFunc_IsInitialized_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void SetDisableMovementForTarget(bool IsDisable, class FName DisableFlagName, class APalCharacter* TargetCharacter, class AController* CallFunc_GetController_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess);
	void FindTalkCameraLocation_NoHitPlayer(const struct FVector& PlayerLocation, const struct FVector& TargetLocation, const struct FVector& TalkCameraLocation, bool* Result, struct FVector* NewTalkCameraLocation, const struct FVector& ResultLocation, bool bResult, int32 TraceDegStep, bool Temp_bool_Variable, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, int32 Temp_int_Variable, int32 CallFunc_Multiply_IntInt_ReturnValue, float CallFunc_Conv_IntToFloat_ReturnValue, int32 CallFunc_Add_IntInt_ReturnValue, const struct FVector& CallFunc_RotateAngleAxis_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, bool CallFunc_LessEqual_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue_1, double CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double CallFunc_BreakVector_Z, const struct FVector& CallFunc_MakeVector_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue_2, const struct FVector& CallFunc_Normal_ReturnValue, double CallFunc_BreakVector_X_1, double CallFunc_BreakVector_Y_1, double CallFunc_BreakVector_Z_1, TArray<class AActor*>& Temp_object_Variable, const struct FVector& CallFunc_MakeVector_ReturnValue_1, const struct FHitResult& CallFunc_LineTraceSingle_OutHit, bool CallFunc_LineTraceSingle_ReturnValue, const struct FVector& CallFunc_Normal_ReturnValue_1, const struct FVector& CallFunc_RotateAngleAxis_ReturnValue_1, bool CallFunc_BreakHitResult_bBlockingHit, bool CallFunc_BreakHitResult_bInitialOverlap, float CallFunc_BreakHitResult_Time, float CallFunc_BreakHitResult_Distance, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class AActor* CallFunc_BreakHitResult_HitActor, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, class FName CallFunc_BreakHitResult_HitBoneName, class FName CallFunc_BreakHitResult_BoneName, int32 CallFunc_BreakHitResult_HitItem, int32 CallFunc_BreakHitResult_ElementIndex, int32 CallFunc_BreakHitResult_FaceIndex, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, double CallFunc_Dot_VectorVector_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue, bool CallFunc_Greater_DoubleDouble_ReturnValue);
	void DetachCamera(double BlendTime, bool CallFunc_IsValid_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess, float CallFunc_SetViewTargetWithBlend_BlendTime_ImplicitCast);
	void AttachCamera(bool NewLocalVar_0, int32 TraceDegStep, const struct FRotator& RotationToTarget, const struct FVector& TalkCameraLocation, const struct FVector& PlayerCameraLocation, const struct FVector& PlayerLocation, const struct FVector& TargetLocation, bool CallFunc_FindTalkCameraLocation_NoHitPlayer_Result, const struct FVector& CallFunc_FindTalkCameraLocation_NoHitPlayer_NewTalkCameraLocation, const struct FTransform& CallFunc_MakeTransform_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValid_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FVector& CallFunc_GetSocketLocation_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, const struct FRotator& CallFunc_MakeRotFromX_ReturnValue, class UPalCharacterCameraComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue_1, const struct FVector& CallFunc_K2_GetComponentLocation_ReturnValue, const struct FVector& CallFunc_Conv_FloatToVector_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue_1, const struct FVector& CallFunc_Multiply_VectorVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue_1, class APalPlayerController* K2Node_DynamicCast_AsPal_Player_Controller, bool K2Node_DynamicCast_bSuccess_1, class AActor* CallFunc_GetViewTarget_ReturnValue);
	void CreateCamera(class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, const struct FTransform& CallFunc_GetTransform_ReturnValue, bool CallFunc_IsValid_ReturnValue, class AActor* CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue, class ABP_PalIncidentCamera_C* CallFunc_FinishSpawningActor_ReturnValue);
	void GetTalkCharacter(class APalCharacter** TalkCharacter, class UObject* CallFunc_GetOccuredObject_ReturnValue, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess);
	void OpenPalShop_Buy(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class UPalHUDDispatchParameter_PalShop* TempWidgetParam, class UObject* WidgetParam, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValidPalShop_ReturnValue);
	void OpenItemShop_Sell(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class UPalHUDDispatchParameterBase* TempWidgetParam, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValidItemShop_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void OpenItemShop_Buy(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, class UPalHUDDispatchParameterBase* TempWidgetParam, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalVenderDataComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValidItemShop_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void CustomFunctionTemplate(const struct FPalNPCTalkSystemCustomFunctionParameters& Param, TScriptInterface<class IPalNPCTalkSystemCustomFunctionInterface> Interface);
	void GetMultiTalk(class FName TalkId, bool* HasTalkData, class UDataTable** TalkData, class FString* TalkSequence, class UBP_MultiTalk_OrderByName_C* K2Node_DynamicCast_AsBP_Multi_Talk_Order_by_Name, bool K2Node_DynamicCast_bSuccess, const class FString& CallFunc_GetStartTalkSequence_Sequence, class UDataTable* CallFunc_GetTalkData_ReturnValue, class UPalNPCManager* CallFunc_GetNPCManager_ReturnValue, TSubclassOf<class UPalNPCMultiTalkHandle> CallFunc_GetNPCMultiTalkClassFromTalkId_ReturnValue, bool CallFunc_IsValidClass_ReturnValue, class UPalNPCMultiTalkHandle* CallFunc_SpawnObject_ReturnValue);
	void GetCharacterTalk(class FName CharacterID, bool* HasTalkData, class UDataTable** TalkData, class UPalNPCManager* CallFunc_GetNPCManager_ReturnValue, class UDataTable* CallFunc_GetNPCCharacterTalkDT_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetOneTalk(class FName TalkId, bool* HasTalkData, class UDataTable** OneTalkData, class UPalNPCManager* CallFunc_GetNPCManager_ReturnValue, class UDataTable* CallFunc_GetNPCOneTalkDTFromTalkId_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetTalkId(class FName* TalkId, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess);
	void GetTalkType(enum class EPalIncidentTalkType* TalkType, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess);
	void Tick_DelayFinish(double DeltaTime, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalNPCInteractionComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_HasAuthority_ReturnValue, class APalPlayerCharacter* K2Node_DynamicCast_AsPal_Player_Character, bool K2Node_DynamicCast_bSuccess, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter_1, class APalNetworkTransmitter* CallFunc_GetNetworkTransmitter_ReturnValue, class UPalNetworkCharacterComponent* CallFunc_GetCharacter_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, bool CallFunc_GreaterEqual_DoubleDouble_ReturnValue);
	void Tick_Talking(double DeltaTime);
	void Setup(bool* Talkable, class APalCharacter* Character, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameterTalk* K2Node_DynamicCast_AsPal_Incident_Dynamic_Parameter_Talk, bool K2Node_DynamicCast_bSuccess, bool K2Node_SwitchEnum_CmpSuccess, bool CallFunc_GetCharacterTalk_HasTalkData, class UDataTable* CallFunc_GetCharacterTalk_TalkData, bool CallFunc_GetMultiTalk_HasTalkData, class UDataTable* CallFunc_GetMultiTalk_TalkData, const class FString& CallFunc_GetMultiTalk_TalkSequence, bool CallFunc_GetOneTalk_HasTalkData, class UDataTable* CallFunc_GetOneTalk_OneTalkData);
	void OnLoaded_C353222C4BEC5555051A4EADFED69384(TSubclassOf<class UObject> Loaded);
	void OnLoaded_4657C8C34673DDF607731EB504BB6BC2(TSubclassOf<class UObject> Loaded);
	void OnLoaded_F24E709545997EF6D7A638BDDC970200(TSubclassOf<class UObject> Loaded);
	void OnItemShopClosed(class UPalHUDDispatchParameterBase* Param);
	void StartTalk();
	void OpenItemShop_AsyncLoadAsset(class UPalHUDDispatchParameterBase* HUDParam);
	void OnTalkUIClosed(class UPalHUDDispatchParameterBase* Param);
	void OnBegin();
	void Tick(float DeltaTime);
	void OnEnd();
	void OnGenerated();
	void OnInitialized();
	void OnForceStop();
	void OnCanceled();
	void OpenPalShop_AsyncLoadAsset(class UPalHUDDispatchParameterBase* HUDParam);
	void OnShopUIClosed(class UPalHUDDispatchParameterBase* Param);
	void ExecuteUbergraph_BP_PalIncidentNPCTalk(int32 EntryPoint, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter, TSubclassOf<class UObject> K2Node_CustomEvent_Loaded_1, class UClass* Temp_class_Variable, class UClass* K2Node_ClassDynamicCast_AsPal_User_Widget_Stackable_UI, bool K2Node_ClassDynamicCast_bSuccess, TSubclassOf<class UObject> K2Node_CustomEvent_Loaded, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class UClass* Temp_class_Variable_1, class UClass* K2Node_ClassDynamicCast_AsPal_User_Widget_Stackable_UI_1, bool K2Node_ClassDynamicCast_bSuccess_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_1, class UPalHUDService* CallFunc_GetHUDService_ReturnValue, class UPalHUDDispatchParameterBase* K2Node_CustomEvent_Param_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_2, class UPalTalkWidgetParameter* CallFunc_SpawnObject_ReturnValue, class UPalHUDService* CallFunc_GetHUDService_ReturnValue_1, const struct FGuid& CallFunc_Push_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_3, class UPalHUDDispatchParameterBase* K2Node_CustomEvent_HUDParam_1, class UPalHUDDispatchParameterBase* K2Node_CustomEvent_Param_1, class UPalTalkWidgetParameter* K2Node_DynamicCast_AsPal_Talk_Widget_Parameter, bool K2Node_DynamicCast_bSuccess, bool CallFunc_Setup_Talkable, float K2Node_Event_DeltaTime, class APalCharacter* CallFunc_GetTalkCharacter_TalkCharacter_1, class UPalHUDDispatchParameterBase* K2Node_CustomEvent_HUDParam, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_4, class UPalHUDService* CallFunc_GetHUDService_ReturnValue_2, class UPalHUDDispatchParameterBase* K2Node_CustomEvent_Param, class UClass* Temp_class_Variable_2, class UClass* K2Node_ClassDynamicCast_AsPal_User_Widget_Stackable_UI_2, bool K2Node_ClassDynamicCast_bSuccess_2, class FName CallFunc_Conv_StringToName_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, const struct FGuid& CallFunc_Push_ReturnValue_1, const struct FGuid& CallFunc_Push_ReturnValue_2, TSubclassOf<class UObject> K2Node_CustomEvent_Loaded_2, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate_5, class APalNetworkTransmitter* CallFunc_GetNetworkTransmitter_ReturnValue, class UPalNetworkCharacterComponent* CallFunc_GetCharacter_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue, class UPalIncidentDynamicParameter* CallFunc_GetDynamicParameter_ReturnValue_1, class APalPlayerCharacter* K2Node_DynamicCast_AsPal_Player_Character, bool K2Node_DynamicCast_bSuccess_1, bool CallFunc_HasAuthority_ReturnValue, double CallFunc_Tick_DelayFinish_DeltaTime_ImplicitCast);
};

}


