#pragma once

// Dumped with Dumper-7!


namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x220 (0x5F8 - 0x3D8)
// BlueprintGeneratedClass BP_PalRandomIncidentNPCSpawner.BP_PalRandomIncidentNPCSpawner_C
class ABP_PalRandomIncidentNPCSpawner_C : public APalRandomIncidentNPCSpawner
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x3D8(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                       DefaultSceneRoot;                                  // 0x3E0(0x8)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                       ReturnRadius;                                      // 0x3E8(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                       WalkRadius;                                        // 0x3F0(0x8)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class FName, struct FF_NPC_PathWalkArray> WalkPathLists;                                     // 0x3F8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UPalIndividualCharacterHandle*> IndividualHandleList;                              // 0x448(0x10)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UPalIndividualCharacterHandle*, struct FPalRandomIncidentSpawnMonsterData> MonsterSpawnData;                                  // 0x458(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UPalIndividualCharacterHandle*, struct FPalRandomIncidentSpawnNPCData> NPCSpawnData;                                      // 0x4A8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UPalIndividualCharacterHandle*, class FName> PathNames;                                         // 0x4F8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<class UPalIndividualCharacterHandle*, class FName> RowNames;                                          // 0x548(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)
	FMulticastInlineDelegateProperty_            GetWalkPathDelegate;                               // 0x598(0x10)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMap<class UPalIndividualCharacterHandle*, struct FVector> SpawnedLocation;                                   // 0x5A8(0x50)(Edit, BlueprintVisible, DisableEditOnInstance)

	static class UClass* StaticClass();
	static class ABP_PalRandomIncidentNPCSpawner_C* GetDefaultObj();

	void GetGroupNo(class UPalIndividualCharacterHandle* IndividualHandle, int32* GroupNo, const struct FPalRandomIncidentSpawnNPCData& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1);
	void GetSpawnedLocation(class UPalIndividualCharacterHandle* Handle, bool* Found, struct FVector* SpawnedLocation, const struct FVector& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void GetSpawnedCharacters(TArray<class AActor*>* SpawnedCharacters, const TArray<class AActor*>& Result, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue, int32 CallFunc_Array_Add_ReturnValue);
	void SetWalkPathList(TMap<class FName, struct FF_NPC_PathWalkArray> PathList);
	class APalCharacter* FindCharacterByName(class FName& Name, class UPalIndividualCharacterHandle* CallFunc_FindIndividualCharacterHandleByName_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue);
	void GetHandleByCharacter(class APalCharacter* Character, class UPalIndividualCharacterHandle** Handle, bool Temp_bool_True_if_break_was_hit_Variable, int32 Temp_int_Array_Index_Variable, bool CallFunc_Not_PreBool_ReturnValue, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_BooleanAND_ReturnValue, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_EqualEqual_ObjectObject_ReturnValue);
	void Setup_Npc_Controller(class ABP_NPCAIController_C* NPCController, class APalCharacter* SpawnedChara, const struct FPalInstanceID& ID, TScriptInterface<class IBPI_GetPalAIBlackboard_C> CallFunc_GetMyBB_self_CastInput, class UBP_PalAIBlackboard_Common_C* CallFunc_GetMyBB_PalBrackboard, class FName CallFunc_Get_Path_Name_PathName, const struct FF_NPC_PathWalkArray& CallFunc_GetWalkPath_WalkPathList, class UPalIndividualCharacterHandle* CallFunc_GetHandleByCharacter_Handle, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FPalRandomIncidentSpawnNPCData& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FVector& CallFunc_Conv_Vector2DToVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, double K2Node_VariableSet_WalkingRadius_BB_ImplicitCast);
	void SetupMonsterController(class ABP_MonsterAIController_Wild_C* Controller, class APalCharacter* SpawnedChara, class UPalIndividualCharacterHandle* CallFunc_GetHandleByCharacter_Handle, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FVector& CallFunc_Conv_Vector2DToVector_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue);
	void Setup_Spawned_Character(const struct FPalInstanceID& ID, class UClass* TmpDefaultAIAction, class UClass* TmpDefaultAction, class APalCharacter* SpawnedChara_0, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class APalCharacter* CallFunc_Get_Character_Character, class AActor* CallFunc_AdjustActorToFloor_ReturnValue, class ABP_MonsterBase_C* K2Node_DynamicCast_AsBP_Monster_Base, bool K2Node_DynamicCast_bSuccess, bool CallFunc_IsValidClass_ReturnValue, class AController* CallFunc_GetController_ReturnValue, class ABP_NPCAIController_C* K2Node_DynamicCast_AsBP_NPCAIController, bool K2Node_DynamicCast_bSuccess_1, class UClass* CallFunc_GetDefaultAction_DefaultAction, class UClass* CallFunc_GetDefaultAction_DefaultAIAction, bool CallFunc_IsValidClass_ReturnValue_1, class UPalIndividualCharacterHandle* CallFunc_FindIndividualHandle_Handle, class FName CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, class AController* CallFunc_GetController_ReturnValue_1, class ABP_MonsterAIController_Wild_C* K2Node_DynamicCast_AsBP_Monster_AIController_Wild, bool K2Node_DynamicCast_bSuccess_2, class AController* CallFunc_GetController_ReturnValue_2, class ABP_NPCAIController_C* K2Node_DynamicCast_AsBP_NPCAIController_1, bool K2Node_DynamicCast_bSuccess_3, class UPalActionComponent* CallFunc_GetComponentByClass_ReturnValue, bool CallFunc_IsValid_ReturnValue, class UPalActionBase* CallFunc_PlayAction_ReturnValue, class AController* CallFunc_GetController_ReturnValue_3, class APalAIController* K2Node_DynamicCast_AsPal_AIController, bool K2Node_DynamicCast_bSuccess_4, bool CallFunc_IsSquad_IsSquad, class UPalIndividualCharacterHandle* CallFunc_FindIndividualHandle_Handle_1, bool CallFunc_IsValid_ReturnValue_1, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue_2, class AController* CallFunc_GetController_ReturnValue_4, class ABP_MonsterAIControllerBase_C* K2Node_DynamicCast_AsBP_Monster_AIController_Base, bool K2Node_DynamicCast_bSuccess_5, int32 CallFunc_GetGroupNo_GroupNo);
	bool IsSpawnedCharacter(class UPalIndividualCharacterHandle* Handle, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_EqualEqual_PalInstanceIDPalInstanceID_ReturnValue);
	void GetWalkPath(class FName PathName, struct FF_NPC_PathWalkArray* WalkPathList, class FName Name_None, bool CallFunc_NotEqual_NameName_ReturnValue, const struct FF_NPC_PathWalkArray& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void Get_Path_Name(const struct FPalInstanceID& ID, class FName* PathName, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, TArray<class UPalIndividualCharacterHandle*>& CallFunc_Map_Keys_Keys, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, bool CallFunc_Less_IntInt_ReturnValue, class FName CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue, bool CallFunc_EqualEqual_PalInstanceIDPalInstanceID_ReturnValue);
	void GetDefaultAction(const struct FPalInstanceID& ID, class UClass** DefaultAction, class UClass** DefaultAIAction, class UPalIndividualCharacterHandle* CallFunc_FindIndividualHandle_Handle, const struct FPalRandomIncidentSpawnNPCData& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1);
	void IsSquad(const struct FPalInstanceID& ID, bool* IsSquad, class UPalIndividualCharacterHandle* CallFunc_FindIndividualHandle_Handle, const struct FPalRandomIncidentSpawnNPCData& CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue, const struct FPalRandomIncidentSpawnMonsterData& CallFunc_Map_Find_Value_1, bool CallFunc_Map_Find_ReturnValue_1);
	void SpawnCharacter(class FName RowName, class FName CharacterID, class FName UniqueName, int32 Level, class UClass* AIController, class FName PathName, const struct FVector& Location, double Radius, double RotZ, int32 SpawnPointIndex, int32 SpawnPointCount, class UPalIndividualCharacterHandle** Handle, struct FVector* SpawnedLocation, const struct FVector& SpawnLocation, class UPalIndividualCharacterHandle* TmpHandle, class FName Name_None, const struct FRotator& CallFunc_K2_GetActorRotation_ReturnValue, float CallFunc_BreakRotator_Roll, float CallFunc_BreakRotator_Pitch, float CallFunc_BreakRotator_Yaw, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, const struct FRotator& CallFunc_MakeRotator_ReturnValue, const struct FVector& CallFunc_Add_VectorVector_ReturnValue, const struct FVector& CallFunc_RandomSpawnLocationByRadiusLineTraceWithWorldLocation_OutLocation, bool CallFunc_RandomSpawnLocationByRadiusLineTraceWithWorldLocation_ReturnValue, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Array_Add_ReturnValue, int32 CallFunc_Max_ReturnValue, bool CallFunc_NotEqual_NameName_ReturnValue, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue, class APlayerController* CallFunc_GetLocalPlayerController_ReturnValue, const struct FGuid& K2Node_MakeStruct_Guid, const struct FNetworkActorSpawnParameters& K2Node_MakeStruct_NetworkActorSpawnParameters, const struct FPalIndividualCharacterSaveParameter& CallFunc_GetInitializedCharacterSaveParemter_outParameter, bool CallFunc_GetInitializedCharacterSaveParemter_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_SpawnNewCharacter_ReturnValue, double CallFunc_Add_DoubleDouble_A_ImplicitCast, float CallFunc_RandomSpawnLocationByRadiusLineTraceWithWorldLocation_Radius_ImplicitCast, float CallFunc_MakeRotator_Yaw_ImplicitCast);
	void Spawn_NPC(class FName RowName, const struct FPalRandomIncidentSpawnNPCData& SpawnData, int32 SpawnPointIndex, int32 SpawnPointCount, const struct FVector& Location, class UPalIndividualCharacterHandle* Handle, const struct FVector& CallFunc_Conv_Vector2DToVector_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_SpawnCharacter_Handle, const struct FVector& CallFunc_SpawnCharacter_SpawnedLocation, double CallFunc_SpawnCharacter_Radius_ImplicitCast, double CallFunc_SpawnCharacter_RotZ_ImplicitCast);
	void Spawn_Monster(class FName RowName, const struct FPalRandomIncidentSpawnMonsterData& SpawnData, int32 SpawnPointIndex, int32 SpawnPointCount, const struct FVector& Location, class UPalIndividualCharacterHandle* Handle, const struct FVector& CallFunc_Conv_Vector2DToVector_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_SpawnCharacter_Handle, const struct FVector& CallFunc_SpawnCharacter_SpawnedLocation, double CallFunc_SpawnCharacter_Radius_ImplicitCast, double CallFunc_SpawnCharacter_RotZ_ImplicitCast);
	void Get_Character(const struct FPalInstanceID& ID, class APalCharacter** Character, class UPalIndividualCharacterHandle* CallFunc_FindIndividualHandle_Handle, class APalCharacter* CallFunc_TryGetIndividualActor_ReturnValue, bool CallFunc_IsValid_ReturnValue, bool CallFunc_IsValid_ReturnValue_1);
	void FindIndividualHandle(const struct FPalInstanceID& ID, class UPalIndividualCharacterHandle** Handle, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue, const struct FPalInstanceID& CallFunc_GetIndividualID_ReturnValue, bool CallFunc_EqualEqual_PalInstanceIDPalInstanceID_ReturnValue);
	void RemoveHandle(class UPalIndividualCharacterHandle* Handle, class UPalIndividualCharacterHandle* TmpHandle, bool CallFunc_Array_RemoveItem_ReturnValue, bool CallFunc_Array_Contains_ReturnValue, bool CallFunc_Map_Remove_ReturnValue, bool CallFunc_Map_Contains_ReturnValue, bool CallFunc_Map_Remove_ReturnValue_1, bool CallFunc_Map_Contains_ReturnValue_1, bool CallFunc_Map_Remove_ReturnValue_2, bool CallFunc_Map_Contains_ReturnValue_2, bool CallFunc_Map_Remove_ReturnValue_3, bool CallFunc_Map_Contains_ReturnValue_3);
	void OnCharacterDestroyed(class AActor* DestroyedActor, class UPalIndividualCharacterHandle* TepHandle, class APalCharacter* K2Node_DynamicCast_AsPal_Character, bool K2Node_DynamicCast_bSuccess, class UPalIndividualCharacterHandle* CallFunc_GetHandleByCharacter_Handle, class FName CallFunc_Map_Find_Value, bool CallFunc_Map_Find_ReturnValue);
	void OnCharacterDespawned(const struct FPalInstanceID& ID);
	void Despawn_Characters(const TArray<class UPalIndividualCharacterHandle*>& TempHandleList, int32 Temp_int_Loop_Counter_Variable, int32 CallFunc_Add_IntInt_ReturnValue, int32 Temp_int_Array_Index_Variable, int32 Temp_int_Array_Index_Variable_1, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item, int32 CallFunc_Array_Length_ReturnValue, class UPalIndividualCharacterHandle* CallFunc_Array_Get_Item_1, int32 CallFunc_Array_Length_ReturnValue_1, int32 Temp_int_Loop_Counter_Variable_1, bool CallFunc_Less_IntInt_ReturnValue, bool CallFunc_Less_IntInt_ReturnValue_1, int32 CallFunc_Add_IntInt_ReturnValue_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, int32 CallFunc_Array_Add_ReturnValue, class UPalCharacterManager* CallFunc_GetCharacterManager_ReturnValue);
	void SpawnMonster(class FName& RowName, struct FPalRandomIncidentSpawnMonsterData& SpawnData, int32 SpawnPointIndex, int32 SpawnPointCount);
	void DespawnCharacters();
	void SpawnNPC(class FName& RowName, struct FPalRandomIncidentSpawnNPCData& SpawnData, int32 SpawnPointIndex, int32 SpawnPointCount);
	void On_Character_Spawned_(const struct FPalInstanceID& ID);
	void _________0(class APalCharacter* InCharacter);
	void ReceiveEndPlay(enum class EEndPlayReason EndPlayReason);
	void ExecuteUbergraph_BP_PalRandomIncidentNPCSpawner(int32 EntryPoint, class FName K2Node_Event_RowName_1, const struct FPalRandomIncidentSpawnMonsterData& K2Node_Event_SpawnData_1, int32 K2Node_Event_SpawnPointIndex_1, int32 K2Node_Event_SpawnPointCount_1, FDelegateProperty_ K2Node_CreateDelegate_OutputDelegate, class FName K2Node_Event_RowName, const struct FPalRandomIncidentSpawnNPCData& K2Node_Event_SpawnData, int32 K2Node_Event_SpawnPointIndex, int32 K2Node_Event_SpawnPointCount, const struct FPalInstanceID& K2Node_CustomEvent_ID, class APalCharacter* CallFunc_Get_Character_Character, class APalCharacter* K2Node_CustomEvent_InCharacter, class UPalCharacterOnCompleteInitializeParameterWrapper* CallFunc_GetOnCompleteInitializeParameterDelegate_ReturnValue, bool CallFunc_IsInitialized_ReturnValue, enum class EEndPlayReason K2Node_Event_EndPlayReason);
	void GetWalkPathDelegate__DelegateSignature(class FName NewParam);
};

}


